/*
Navicat Oracle Data Transfer
Oracle Client Version : 11.2.0.1.0

Source Server         : 139.224.69.242（xxl）
Source Server Version : 110200
Source Host           : 139.224.69.242:1521
Source Schema         : XXL

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2017-07-13 18:40:03
*/


-- ----------------------------
-- Table structure for XXL_BLOB_TRIGGERS
-- ----------------------------
DROP TABLE "XXL"."XXL_BLOB_TRIGGERS";
CREATE TABLE "XXL"."XXL_BLOB_TRIGGERS" (
"SCHED_NAME" VARCHAR2(120 BYTE) NOT NULL ,
"TRIGGER_NAME" VARCHAR2(200 BYTE) NOT NULL ,
"TRIGGER_GROUP" VARCHAR2(200 BYTE) NOT NULL ,
"BLOB_DATA" BLOB NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of XXL_BLOB_TRIGGERS
-- ----------------------------

-- ----------------------------
-- Table structure for XXL_CALENDARS
-- ----------------------------
DROP TABLE "XXL"."XXL_CALENDARS";
CREATE TABLE "XXL"."XXL_CALENDARS" (
"SCHED_NAME" VARCHAR2(120 BYTE) NOT NULL ,
"CALENDAR_NAME" VARCHAR2(200 BYTE) NOT NULL ,
"CALENDAR" BLOB NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of XXL_CALENDARS
-- ----------------------------

-- ----------------------------
-- Table structure for XXL_CRON_TRIGGERS
-- ----------------------------
DROP TABLE "XXL"."XXL_CRON_TRIGGERS";
CREATE TABLE "XXL"."XXL_CRON_TRIGGERS" (
"SCHED_NAME" VARCHAR2(120 BYTE) NOT NULL ,
"TRIGGER_NAME" VARCHAR2(200 BYTE) NOT NULL ,
"TRIGGER_GROUP" VARCHAR2(200 BYTE) NOT NULL ,
"CRON_EXPRESSION" VARCHAR2(120 BYTE) NOT NULL ,
"TIME_ZONE_ID" VARCHAR2(80 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of XXL_CRON_TRIGGERS
-- ----------------------------


-- ----------------------------
-- Table structure for XXL_FIRED_TRIGGERS
-- ----------------------------
DROP TABLE "XXL"."XXL_FIRED_TRIGGERS";
CREATE TABLE "XXL"."XXL_FIRED_TRIGGERS" (
"SCHED_NAME" VARCHAR2(120 BYTE) NOT NULL ,
"ENTRY_ID" VARCHAR2(95 BYTE) NOT NULL ,
"TRIGGER_NAME" VARCHAR2(200 BYTE) NOT NULL ,
"TRIGGER_GROUP" VARCHAR2(200 BYTE) NOT NULL ,
"INSTANCE_NAME" VARCHAR2(200 BYTE) NOT NULL ,
"FIRED_TIME" NUMBER(13) NOT NULL ,
"SCHED_TIME" NUMBER(13) NOT NULL ,
"PRIORITY" NUMBER(13) NOT NULL ,
"STATE" VARCHAR2(16 BYTE) NOT NULL ,
"JOB_NAME" VARCHAR2(200 BYTE) NULL ,
"JOB_GROUP" VARCHAR2(200 BYTE) NULL ,
"IS_NONCONCURRENT" VARCHAR2(1 BYTE) NULL ,
"REQUESTS_RECOVERY" VARCHAR2(1 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of XXL_FIRED_TRIGGERS
-- ----------------------------

-- ----------------------------
-- Table structure for XXL_JOB_DETAILS
-- ----------------------------
DROP TABLE "XXL"."XXL_JOB_DETAILS";
CREATE TABLE "XXL"."XXL_JOB_DETAILS" (
"SCHED_NAME" VARCHAR2(120 BYTE) NOT NULL ,
"JOB_NAME" VARCHAR2(200 BYTE) NOT NULL ,
"JOB_GROUP" VARCHAR2(200 BYTE) NOT NULL ,
"DESCRIPTION" VARCHAR2(250 BYTE) NULL ,
"JOB_CLASS_NAME" VARCHAR2(250 BYTE) NOT NULL ,
"IS_DURABLE" VARCHAR2(1 BYTE) NOT NULL ,
"IS_NONCONCURRENT" VARCHAR2(1 BYTE) NOT NULL ,
"IS_UPDATE_DATA" VARCHAR2(1 BYTE) NOT NULL ,
"REQUESTS_RECOVERY" VARCHAR2(1 BYTE) NOT NULL ,
"JOB_DATA" BLOB NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of XXL_JOB_DETAILS
-- ----------------------------

-- ----------------------------
-- Table structure for XXL_LOCKS
-- ----------------------------
DROP TABLE "XXL"."XXL_LOCKS";
CREATE TABLE "XXL"."XXL_LOCKS" (
"SCHED_NAME" VARCHAR2(120 BYTE) NOT NULL ,
"LOCK_NAME" VARCHAR2(40 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of XXL_LOCKS
-- ----------------------------

-- ----------------------------
-- Table structure for XXL_PAUSED_TRIGGER_GRPS
-- ----------------------------
DROP TABLE "XXL"."XXL_PAUSED_TRIGGER_GRPS";
CREATE TABLE "XXL"."XXL_PAUSED_TRIGGER_GRPS" (
"SCHED_NAME" VARCHAR2(120 BYTE) NOT NULL ,
"TRIGGER_GROUP" VARCHAR2(200 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of XXL_PAUSED_TRIGGER_GRPS
-- ----------------------------

-- ----------------------------
-- Table structure for XXL_SCHEDULER_STATE
-- ----------------------------
DROP TABLE "XXL"."XXL_SCHEDULER_STATE";
CREATE TABLE "XXL"."XXL_SCHEDULER_STATE" (
"SCHED_NAME" VARCHAR2(120 BYTE) NOT NULL ,
"INSTANCE_NAME" VARCHAR2(200 BYTE) NOT NULL ,
"LAST_CHECKIN_TIME" NUMBER(13) NOT NULL ,
"CHECKIN_INTERVAL" NUMBER(13) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of XXL_SCHEDULER_STATE
-- ----------------------------

-- ----------------------------
-- Table structure for XXL_SIMPLE_TRIGGERS
-- ----------------------------
DROP TABLE "XXL"."XXL_SIMPLE_TRIGGERS";
CREATE TABLE "XXL"."XXL_SIMPLE_TRIGGERS" (
"SCHED_NAME" VARCHAR2(120 BYTE) NOT NULL ,
"TRIGGER_NAME" VARCHAR2(200 BYTE) NOT NULL ,
"TRIGGER_GROUP" VARCHAR2(200 BYTE) NOT NULL ,
"REPEAT_COUNT" NUMBER(7) NOT NULL ,
"REPEAT_INTERVAL" NUMBER(12) NOT NULL ,
"TIMES_TRIGGERED" NUMBER(10) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of XXL_SIMPLE_TRIGGERS
-- ----------------------------

-- ----------------------------
-- Table structure for XXL_SIMPROP_TRIGGERS
-- ----------------------------
DROP TABLE "XXL"."XXL_SIMPROP_TRIGGERS";
CREATE TABLE "XXL"."XXL_SIMPROP_TRIGGERS" (
"SCHED_NAME" VARCHAR2(120 BYTE) NOT NULL ,
"TRIGGER_NAME" VARCHAR2(200 BYTE) NOT NULL ,
"TRIGGER_GROUP" VARCHAR2(200 BYTE) NOT NULL ,
"STR_PROP_1" VARCHAR2(512 BYTE) NULL ,
"STR_PROP_2" VARCHAR2(512 BYTE) NULL ,
"STR_PROP_3" VARCHAR2(512 BYTE) NULL ,
"INT_PROP_1" NUMBER(10) NULL ,
"INT_PROP_2" NUMBER(10) NULL ,
"LONG_PROP_1" NUMBER(13) NULL ,
"LONG_PROP_2" NUMBER(13) NULL ,
"DEC_PROP_1" NUMBER(13,4) NULL ,
"DEC_PROP_2" NUMBER(13,4) NULL ,
"BOOL_PROP_1" VARCHAR2(1 BYTE) NULL ,
"BOOL_PROP_2" VARCHAR2(1 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of XXL_SIMPROP_TRIGGERS
-- ----------------------------

-- ----------------------------
-- Table structure for XXL_TRIGGER_GROUP
-- ----------------------------
DROP TABLE "XXL"."XXL_TRIGGER_GROUP";
CREATE TABLE "XXL"."XXL_TRIGGER_GROUP" (
"ID" NUMBER(11) NOT NULL ,
"APP_NAME" VARCHAR2(64 BYTE) NOT NULL ,
"TITLE" VARCHAR2(12 BYTE) NOT NULL ,
"ORDER" NUMBER(4) DEFAULT '0'  NULL ,
"ADDRESS_TYPE" NUMBER(4) DEFAULT '0'  NULL ,
"ADDRESS_LIST" VARCHAR2(200 BYTE) DEFAULT NULL  NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_GROUP"."APP_NAME" IS '执行器AppName';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_GROUP"."TITLE" IS '执行器名称';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_GROUP"."ORDER" IS '排序';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_GROUP"."ADDRESS_TYPE" IS '执行器地址类型：0=自动注册、1=手动录入';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_GROUP"."ADDRESS_LIST" IS '执行器地址列表，多地址逗号分隔';

-- ----------------------------
-- Records of XXL_TRIGGER_GROUP
-- ----------------------------

-- ----------------------------
-- Table structure for XXL_TRIGGER_INFO
-- ----------------------------
DROP TABLE "XXL"."XXL_TRIGGER_INFO";
CREATE TABLE "XXL"."XXL_TRIGGER_INFO" (
"ID" NUMBER NOT NULL ,
"JOB_GROUP" NUMBER NOT NULL ,
"JOB_CRON" VARCHAR2(128 BYTE) NOT NULL ,
"JOB_DESC" VARCHAR2(255 BYTE) NOT NULL ,
"ADD_TIME" TIMESTAMP(6)  DEFAULT NULL  NULL ,
"UPDATE_TIME" TIMESTAMP(6)  DEFAULT NULL  NULL ,
"AUTHOR" VARCHAR2(64 BYTE) DEFAULT NULL  NULL ,
"ALARM_EMAIL" VARCHAR2(255 BYTE) DEFAULT NULL  NULL ,
"EXECUTOR_ROUTE_STRATEGY" VARCHAR2(50 BYTE) DEFAULT NULL  NULL ,
"EXECUTOR_HANDLER" VARCHAR2(255 BYTE) DEFAULT NULL  NULL ,
"EXECUTOR_PARAM" VARCHAR2(255 BYTE) DEFAULT NULL  NULL ,
"EXECUTOR_BLOCK_STRATEGY" VARCHAR2(50 BYTE) DEFAULT NULL  NULL ,
"EXECUTOR_FAIL_STRATEGY" VARCHAR2(50 BYTE) DEFAULT NULL  NULL ,
"GLUE_TYPE" VARCHAR2(50 BYTE) NOT NULL ,
"GLUE_SOURCE" CLOB NULL ,
"GLUE_REMARK" VARCHAR2(128 BYTE) DEFAULT NULL  NULL ,
"GLUE_UPDATETIME" TIMESTAMP(6)  DEFAULT NULL  NULL ,
"CHILD_JOBKEY" VARCHAR2(255 BYTE) DEFAULT NULL  NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_INFO"."JOB_GROUP" IS '执行器主键ID';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_INFO"."JOB_CRON" IS '任务执行CRON';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_INFO"."AUTHOR" IS '作者';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_INFO"."ALARM_EMAIL" IS '报警邮件';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_INFO"."EXECUTOR_ROUTE_STRATEGY" IS '执行器路由策略';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_INFO"."EXECUTOR_HANDLER" IS '执行器任务handler';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_INFO"."EXECUTOR_PARAM" IS '执行器任务参数';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_INFO"."EXECUTOR_BLOCK_STRATEGY" IS '阻塞处理策略';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_INFO"."EXECUTOR_FAIL_STRATEGY" IS '失败处理策略';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_INFO"."GLUE_TYPE" IS 'GLUE类型';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_INFO"."GLUE_SOURCE" IS 'GLUE源代码';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_INFO"."GLUE_REMARK" IS 'GLUE备注';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_INFO"."GLUE_UPDATETIME" IS 'GLUE更新时间';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_INFO"."CHILD_JOBKEY" IS '子任务Key';

-- ----------------------------
-- Records of XXL_TRIGGER_INFO
-- ----------------------------

-- ----------------------------
-- Table structure for XXL_TRIGGER_LOG
-- ----------------------------
DROP TABLE "XXL"."XXL_TRIGGER_LOG";
CREATE TABLE "XXL"."XXL_TRIGGER_LOG" (
"ID" NUMBER NOT NULL ,
"JOB_GROUP" NUMBER NOT NULL ,
"JOB_ID" NUMBER NOT NULL ,
"GLUE_TYPE" VARCHAR2(50 BYTE) DEFAULT NULL  NULL ,
"EXECUTOR_ADDRESS" VARCHAR2(255 BYTE) DEFAULT NULL  NULL ,
"EXECUTOR_HANDLER" VARCHAR2(255 BYTE) DEFAULT NULL  NULL ,
"EXECUTOR_PARAM" VARCHAR2(255 BYTE) DEFAULT NULL  NULL ,
"TRIGGER_TIME" TIMESTAMP(6)  DEFAULT NULL  NULL ,
"TRIGGER_CODE" VARCHAR2(255 BYTE) DEFAULT NULL  NULL ,
"TRIGGER_MSG" VARCHAR2(2048 BYTE) DEFAULT NULL  NULL ,
"HANDLE_TIME" TIMESTAMP(6)  DEFAULT NULL  NULL ,
"HANDLE_CODE" VARCHAR2(255 BYTE) DEFAULT NULL  NULL ,
"HANDLE_MSG" VARCHAR2(2048 BYTE) DEFAULT NULL  NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_LOG"."JOB_GROUP" IS '执行器主键ID';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_LOG"."JOB_ID" IS '任务，主键ID';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_LOG"."GLUE_TYPE" IS 'GLUE类型';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_LOG"."EXECUTOR_ADDRESS" IS '执行器地址，本次执行的地址';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_LOG"."EXECUTOR_HANDLER" IS '执行器任务handler';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_LOG"."EXECUTOR_PARAM" IS 'executor_param';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_LOG"."TRIGGER_TIME" IS '调度-时间';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_LOG"."TRIGGER_CODE" IS '调度-结果';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_LOG"."TRIGGER_MSG" IS '调度-日志';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_LOG"."HANDLE_TIME" IS '执行-时间';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_LOG"."HANDLE_CODE" IS '执行-状态';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_LOG"."HANDLE_MSG" IS '执行-日志';

-- ----------------------------
-- Records of XXL_TRIGGER_LOG
-- ----------------------------

-- ----------------------------
-- Table structure for XXL_TRIGGER_LOGGLUE
-- ----------------------------
DROP TABLE "XXL"."XXL_TRIGGER_LOGGLUE";
CREATE TABLE "XXL"."XXL_TRIGGER_LOGGLUE" (
"ID" NUMBER NOT NULL ,
"JOB_ID" NUMBER NOT NULL ,
"GLUE_TYPE" VARCHAR2(50 BYTE) DEFAULT NULL  NULL ,
"GLUE_SOURCE" CLOB NULL ,
"GLUE_REMARK" VARCHAR2(128 BYTE) NOT NULL ,
"ADD_TIME" TIMESTAMP(6)  NULL ,
"UPDATE_TIME" TIMESTAMP(6)  NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_LOGGLUE"."JOB_ID" IS '任务，主键ID';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_LOGGLUE"."GLUE_TYPE" IS 'GLUE类型';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_LOGGLUE"."GLUE_SOURCE" IS 'GLUE源代码';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_LOGGLUE"."GLUE_REMARK" IS 'GLUE备注';

-- ----------------------------
-- Records of XXL_TRIGGER_LOGGLUE
-- ----------------------------

-- ----------------------------
-- Table structure for XXL_TRIGGER_REGISTRY
-- ----------------------------
DROP TABLE "XXL"."XXL_TRIGGER_REGISTRY";
CREATE TABLE "XXL"."XXL_TRIGGER_REGISTRY" (
"ID" NUMBER NOT NULL ,
"REGISTRY_GROUP" VARCHAR2(255 BYTE) NOT NULL ,
"REGISTRY_KEY" VARCHAR2(255 BYTE) NOT NULL ,
"REGISTRY_VALUE" VARCHAR2(255 BYTE) NOT NULL ,
"UPDATE_TIME" TIMESTAMP(6)  NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of XXL_TRIGGER_REGISTRY
-- ----------------------------

-- ----------------------------
-- Table structure for XXL_TRIGGERS
-- ----------------------------
DROP TABLE "XXL"."XXL_TRIGGERS";
CREATE TABLE "XXL"."XXL_TRIGGERS" (
"SCHED_NAME" VARCHAR2(120 BYTE) NOT NULL ,
"TRIGGER_NAME" VARCHAR2(200 BYTE) NOT NULL ,
"TRIGGER_GROUP" VARCHAR2(200 BYTE) NOT NULL ,
"JOB_NAME" VARCHAR2(200 BYTE) NOT NULL ,
"JOB_GROUP" VARCHAR2(200 BYTE) NOT NULL ,
"DESCRIPTION" VARCHAR2(250 BYTE) NULL ,
"NEXT_FIRE_TIME" NUMBER(13) NULL ,
"PREV_FIRE_TIME" NUMBER(13) NULL ,
"PRIORITY" NUMBER(13) NULL ,
"TRIGGER_STATE" VARCHAR2(16 BYTE) NOT NULL ,
"TRIGGER_TYPE" VARCHAR2(8 BYTE) NOT NULL ,
"START_TIME" NUMBER(13) NOT NULL ,
"END_TIME" NUMBER(13) NULL ,
"CALENDAR_NAME" VARCHAR2(200 BYTE) NULL ,
"MISFIRE_INSTR" NUMBER(2) NULL ,
"JOB_DATA" BLOB NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of XXL_TRIGGERS
-- ----------------------------

-- ----------------------------
-- Sequence structure for TRIGGER_GROUP_SEQ
-- ----------------------------
DROP SEQUENCE "XXL"."TRIGGER_GROUP_SEQ";
CREATE SEQUENCE "XXL"."TRIGGER_GROUP_SEQ"
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999999999999999999999
 START WITH 1
 NOCACHE ;

-- ----------------------------
-- Sequence structure for TRIGGER_GROUP_SEQUENCE
-- ----------------------------
DROP SEQUENCE "XXL"."TRIGGER_GROUP_SEQUENCE";
CREATE SEQUENCE "XXL"."TRIGGER_GROUP_SEQUENCE"
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999999999999999999999
 START WITH 4
 NOCACHE ;

-- ----------------------------
-- Sequence structure for TRIGGER_INFO_SEQ
-- ----------------------------
DROP SEQUENCE "XXL"."TRIGGER_INFO_SEQ";
CREATE SEQUENCE "XXL"."TRIGGER_INFO_SEQ"
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999999999999999999999
 START WITH 27
 NOCACHE ;

-- ----------------------------
-- Sequence structure for TRIGGER_INFO_SEQUENCE
-- ----------------------------
DROP SEQUENCE "XXL"."TRIGGER_INFO_SEQUENCE";
CREATE SEQUENCE "XXL"."TRIGGER_INFO_SEQUENCE"
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999999999999999999999
 START WITH 9
 NOCACHE ;

-- ----------------------------
-- Sequence structure for TRIGGER_LOG_SEQ
-- ----------------------------
DROP SEQUENCE "XXL"."TRIGGER_LOG_SEQ";
CREATE SEQUENCE "XXL"."TRIGGER_LOG_SEQ"
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999999999999999999999
 START WITH 2
 NOCACHE ;

-- ----------------------------
-- Sequence structure for TRIGGER_LOG_SEQUENCE
-- ----------------------------
DROP SEQUENCE "XXL"."TRIGGER_LOG_SEQUENCE";
CREATE SEQUENCE "XXL"."TRIGGER_LOG_SEQUENCE"
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999999999999999999999
 START WITH 1677
 NOCACHE ;

-- ----------------------------
-- Sequence structure for TRIGGER_LOGGLUE_SEQ
-- ----------------------------
DROP SEQUENCE "XXL"."TRIGGER_LOGGLUE_SEQ";
CREATE SEQUENCE "XXL"."TRIGGER_LOGGLUE_SEQ"
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999999999999999999999
 START WITH 1
 NOCACHE ;

-- ----------------------------
-- Sequence structure for TRIGGER_LOGGLUE_SEQUENCE
-- ----------------------------
DROP SEQUENCE "XXL"."TRIGGER_LOGGLUE_SEQUENCE";
CREATE SEQUENCE "XXL"."TRIGGER_LOGGLUE_SEQUENCE"
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999999999999999999999
 START WITH 2
 NOCACHE ;

-- ----------------------------
-- Sequence structure for TRIGGER_REGISTRY_SEQ
-- ----------------------------
DROP SEQUENCE "XXL"."TRIGGER_REGISTRY_SEQ";
CREATE SEQUENCE "XXL"."TRIGGER_REGISTRY_SEQ"
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999999999999999999999
 START WITH 27
 NOCACHE ;

-- ----------------------------
-- Sequence structure for TRIGGER_REGISTRY_SEQUENCE
-- ----------------------------
DROP SEQUENCE "XXL"."TRIGGER_REGISTRY_SEQUENCE";
CREATE SEQUENCE "XXL"."TRIGGER_REGISTRY_SEQUENCE"
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999999999999999999999
 START WITH 24
 NOCACHE ;

-- ----------------------------
-- Indexes structure for table XXL_BLOB_TRIGGERS
-- ----------------------------

-- ----------------------------
-- Checks structure for table XXL_BLOB_TRIGGERS
-- ----------------------------
ALTER TABLE "XXL"."XXL_BLOB_TRIGGERS" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_BLOB_TRIGGERS" ADD CHECK ("TRIGGER_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_BLOB_TRIGGERS" ADD CHECK ("TRIGGER_GROUP" IS NOT NULL);
ALTER TABLE "XXL"."XXL_BLOB_TRIGGERS" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_BLOB_TRIGGERS" ADD CHECK ("TRIGGER_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_BLOB_TRIGGERS" ADD CHECK ("TRIGGER_GROUP" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table XXL_BLOB_TRIGGERS
-- ----------------------------
ALTER TABLE "XXL"."XXL_BLOB_TRIGGERS" ADD PRIMARY KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP");

-- ----------------------------
-- Indexes structure for table XXL_CALENDARS
-- ----------------------------

-- ----------------------------
-- Checks structure for table XXL_CALENDARS
-- ----------------------------
ALTER TABLE "XXL"."XXL_CALENDARS" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_CALENDARS" ADD CHECK ("CALENDAR_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_CALENDARS" ADD CHECK ("CALENDAR" IS NOT NULL);
ALTER TABLE "XXL"."XXL_CALENDARS" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_CALENDARS" ADD CHECK ("CALENDAR_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_CALENDARS" ADD CHECK ("CALENDAR" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table XXL_CALENDARS
-- ----------------------------
ALTER TABLE "XXL"."XXL_CALENDARS" ADD PRIMARY KEY ("SCHED_NAME", "CALENDAR_NAME");

-- ----------------------------
-- Indexes structure for table XXL_CRON_TRIGGERS
-- ----------------------------

-- ----------------------------
-- Checks structure for table XXL_CRON_TRIGGERS
-- ----------------------------
ALTER TABLE "XXL"."XXL_CRON_TRIGGERS" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_CRON_TRIGGERS" ADD CHECK ("TRIGGER_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_CRON_TRIGGERS" ADD CHECK ("TRIGGER_GROUP" IS NOT NULL);
ALTER TABLE "XXL"."XXL_CRON_TRIGGERS" ADD CHECK ("CRON_EXPRESSION" IS NOT NULL);
ALTER TABLE "XXL"."XXL_CRON_TRIGGERS" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_CRON_TRIGGERS" ADD CHECK ("TRIGGER_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_CRON_TRIGGERS" ADD CHECK ("TRIGGER_GROUP" IS NOT NULL);
ALTER TABLE "XXL"."XXL_CRON_TRIGGERS" ADD CHECK ("CRON_EXPRESSION" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table XXL_CRON_TRIGGERS
-- ----------------------------
ALTER TABLE "XXL"."XXL_CRON_TRIGGERS" ADD PRIMARY KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP");

-- ----------------------------
-- Indexes structure for table XXL_FIRED_TRIGGERS
-- ----------------------------


-- ----------------------------
-- Checks structure for table XXL_FIRED_TRIGGERS
-- ----------------------------
ALTER TABLE "XXL"."XXL_FIRED_TRIGGERS" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_FIRED_TRIGGERS" ADD CHECK ("ENTRY_ID" IS NOT NULL);
ALTER TABLE "XXL"."XXL_FIRED_TRIGGERS" ADD CHECK ("TRIGGER_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_FIRED_TRIGGERS" ADD CHECK ("TRIGGER_GROUP" IS NOT NULL);
ALTER TABLE "XXL"."XXL_FIRED_TRIGGERS" ADD CHECK ("INSTANCE_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_FIRED_TRIGGERS" ADD CHECK ("FIRED_TIME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_FIRED_TRIGGERS" ADD CHECK ("SCHED_TIME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_FIRED_TRIGGERS" ADD CHECK ("PRIORITY" IS NOT NULL);
ALTER TABLE "XXL"."XXL_FIRED_TRIGGERS" ADD CHECK ("STATE" IS NOT NULL);
ALTER TABLE "XXL"."XXL_FIRED_TRIGGERS" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_FIRED_TRIGGERS" ADD CHECK ("ENTRY_ID" IS NOT NULL);
ALTER TABLE "XXL"."XXL_FIRED_TRIGGERS" ADD CHECK ("TRIGGER_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_FIRED_TRIGGERS" ADD CHECK ("TRIGGER_GROUP" IS NOT NULL);
ALTER TABLE "XXL"."XXL_FIRED_TRIGGERS" ADD CHECK ("INSTANCE_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_FIRED_TRIGGERS" ADD CHECK ("FIRED_TIME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_FIRED_TRIGGERS" ADD CHECK ("SCHED_TIME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_FIRED_TRIGGERS" ADD CHECK ("PRIORITY" IS NOT NULL);
ALTER TABLE "XXL"."XXL_FIRED_TRIGGERS" ADD CHECK ("STATE" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table XXL_FIRED_TRIGGERS
-- ----------------------------
ALTER TABLE "XXL"."XXL_FIRED_TRIGGERS" ADD PRIMARY KEY ("SCHED_NAME", "ENTRY_ID");

-- ----------------------------
-- Indexes structure for table XXL_JOB_DETAILS
-- ----------------------------


-- ----------------------------
-- Checks structure for table XXL_JOB_DETAILS
-- ----------------------------
ALTER TABLE "XXL"."XXL_JOB_DETAILS" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_JOB_DETAILS" ADD CHECK ("JOB_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_JOB_DETAILS" ADD CHECK ("JOB_GROUP" IS NOT NULL);
ALTER TABLE "XXL"."XXL_JOB_DETAILS" ADD CHECK ("JOB_CLASS_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_JOB_DETAILS" ADD CHECK ("IS_DURABLE" IS NOT NULL);
ALTER TABLE "XXL"."XXL_JOB_DETAILS" ADD CHECK ("IS_NONCONCURRENT" IS NOT NULL);
ALTER TABLE "XXL"."XXL_JOB_DETAILS" ADD CHECK ("IS_UPDATE_DATA" IS NOT NULL);
ALTER TABLE "XXL"."XXL_JOB_DETAILS" ADD CHECK ("REQUESTS_RECOVERY" IS NOT NULL);
ALTER TABLE "XXL"."XXL_JOB_DETAILS" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_JOB_DETAILS" ADD CHECK ("JOB_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_JOB_DETAILS" ADD CHECK ("JOB_GROUP" IS NOT NULL);
ALTER TABLE "XXL"."XXL_JOB_DETAILS" ADD CHECK ("JOB_CLASS_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_JOB_DETAILS" ADD CHECK ("IS_DURABLE" IS NOT NULL);
ALTER TABLE "XXL"."XXL_JOB_DETAILS" ADD CHECK ("IS_NONCONCURRENT" IS NOT NULL);
ALTER TABLE "XXL"."XXL_JOB_DETAILS" ADD CHECK ("IS_UPDATE_DATA" IS NOT NULL);
ALTER TABLE "XXL"."XXL_JOB_DETAILS" ADD CHECK ("REQUESTS_RECOVERY" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table XXL_JOB_DETAILS
-- ----------------------------
ALTER TABLE "XXL"."XXL_JOB_DETAILS" ADD PRIMARY KEY ("SCHED_NAME", "JOB_NAME", "JOB_GROUP");

-- ----------------------------
-- Indexes structure for table XXL_LOCKS
-- ----------------------------

-- ----------------------------
-- Checks structure for table XXL_LOCKS
-- ----------------------------
ALTER TABLE "XXL"."XXL_LOCKS" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_LOCKS" ADD CHECK ("LOCK_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_LOCKS" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_LOCKS" ADD CHECK ("LOCK_NAME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table XXL_LOCKS
-- ----------------------------
ALTER TABLE "XXL"."XXL_LOCKS" ADD PRIMARY KEY ("SCHED_NAME", "LOCK_NAME");

-- ----------------------------
-- Indexes structure for table XXL_PAUSED_TRIGGER_GRPS
-- ----------------------------

-- ----------------------------
-- Checks structure for table XXL_PAUSED_TRIGGER_GRPS
-- ----------------------------
ALTER TABLE "XXL"."XXL_PAUSED_TRIGGER_GRPS" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_PAUSED_TRIGGER_GRPS" ADD CHECK ("TRIGGER_GROUP" IS NOT NULL);
ALTER TABLE "XXL"."XXL_PAUSED_TRIGGER_GRPS" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_PAUSED_TRIGGER_GRPS" ADD CHECK ("TRIGGER_GROUP" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table XXL_PAUSED_TRIGGER_GRPS
-- ----------------------------
ALTER TABLE "XXL"."XXL_PAUSED_TRIGGER_GRPS" ADD PRIMARY KEY ("SCHED_NAME", "TRIGGER_GROUP");

-- ----------------------------
-- Indexes structure for table XXL_SCHEDULER_STATE
-- ----------------------------

-- ----------------------------
-- Checks structure for table XXL_SCHEDULER_STATE
-- ----------------------------
ALTER TABLE "XXL"."XXL_SCHEDULER_STATE" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_SCHEDULER_STATE" ADD CHECK ("INSTANCE_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_SCHEDULER_STATE" ADD CHECK ("LAST_CHECKIN_TIME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_SCHEDULER_STATE" ADD CHECK ("CHECKIN_INTERVAL" IS NOT NULL);
ALTER TABLE "XXL"."XXL_SCHEDULER_STATE" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_SCHEDULER_STATE" ADD CHECK ("INSTANCE_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_SCHEDULER_STATE" ADD CHECK ("LAST_CHECKIN_TIME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_SCHEDULER_STATE" ADD CHECK ("CHECKIN_INTERVAL" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table XXL_SCHEDULER_STATE
-- ----------------------------
ALTER TABLE "XXL"."XXL_SCHEDULER_STATE" ADD PRIMARY KEY ("SCHED_NAME", "INSTANCE_NAME");

-- ----------------------------
-- Indexes structure for table XXL_SIMPLE_TRIGGERS
-- ----------------------------

-- ----------------------------
-- Checks structure for table XXL_SIMPLE_TRIGGERS
-- ----------------------------
ALTER TABLE "XXL"."XXL_SIMPLE_TRIGGERS" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_SIMPLE_TRIGGERS" ADD CHECK ("TRIGGER_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_SIMPLE_TRIGGERS" ADD CHECK ("TRIGGER_GROUP" IS NOT NULL);
ALTER TABLE "XXL"."XXL_SIMPLE_TRIGGERS" ADD CHECK ("REPEAT_COUNT" IS NOT NULL);
ALTER TABLE "XXL"."XXL_SIMPLE_TRIGGERS" ADD CHECK ("REPEAT_INTERVAL" IS NOT NULL);
ALTER TABLE "XXL"."XXL_SIMPLE_TRIGGERS" ADD CHECK ("TIMES_TRIGGERED" IS NOT NULL);
ALTER TABLE "XXL"."XXL_SIMPLE_TRIGGERS" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_SIMPLE_TRIGGERS" ADD CHECK ("TRIGGER_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_SIMPLE_TRIGGERS" ADD CHECK ("TRIGGER_GROUP" IS NOT NULL);
ALTER TABLE "XXL"."XXL_SIMPLE_TRIGGERS" ADD CHECK ("REPEAT_COUNT" IS NOT NULL);
ALTER TABLE "XXL"."XXL_SIMPLE_TRIGGERS" ADD CHECK ("REPEAT_INTERVAL" IS NOT NULL);
ALTER TABLE "XXL"."XXL_SIMPLE_TRIGGERS" ADD CHECK ("TIMES_TRIGGERED" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table XXL_SIMPLE_TRIGGERS
-- ----------------------------
ALTER TABLE "XXL"."XXL_SIMPLE_TRIGGERS" ADD PRIMARY KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP");

-- ----------------------------
-- Indexes structure for table XXL_SIMPROP_TRIGGERS
-- ----------------------------

-- ----------------------------
-- Checks structure for table XXL_SIMPROP_TRIGGERS
-- ----------------------------
ALTER TABLE "XXL"."XXL_SIMPROP_TRIGGERS" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_SIMPROP_TRIGGERS" ADD CHECK ("TRIGGER_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_SIMPROP_TRIGGERS" ADD CHECK ("TRIGGER_GROUP" IS NOT NULL);
ALTER TABLE "XXL"."XXL_SIMPROP_TRIGGERS" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_SIMPROP_TRIGGERS" ADD CHECK ("TRIGGER_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_SIMPROP_TRIGGERS" ADD CHECK ("TRIGGER_GROUP" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table XXL_SIMPROP_TRIGGERS
-- ----------------------------
ALTER TABLE "XXL"."XXL_SIMPROP_TRIGGERS" ADD PRIMARY KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP");

-- ----------------------------
-- Checks structure for table XXL_TRIGGER_GROUP
-- ----------------------------
ALTER TABLE "XXL"."XXL_TRIGGER_GROUP" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_GROUP" ADD CHECK ("APP_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_GROUP" ADD CHECK ("TITLE" IS NOT NULL);

-- ----------------------------
-- Indexes structure for table XXL_TRIGGER_INFO
-- ----------------------------

-- ----------------------------
-- Checks structure for table XXL_TRIGGER_INFO
-- ----------------------------
ALTER TABLE "XXL"."XXL_TRIGGER_INFO" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_INFO" ADD CHECK ("JOB_GROUP" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_INFO" ADD CHECK ("JOB_CRON" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_INFO" ADD CHECK ("JOB_DESC" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_INFO" ADD CHECK ("GLUE_TYPE" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_INFO" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_INFO" ADD CHECK ("JOB_GROUP" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_INFO" ADD CHECK ("JOB_CRON" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_INFO" ADD CHECK ("JOB_DESC" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_INFO" ADD CHECK ("GLUE_TYPE" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_INFO" ADD CHECK (ID IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_INFO" ADD CHECK (JOB_GROUP IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_INFO" ADD CHECK (JOB_CRON IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_INFO" ADD CHECK (JOB_DESC IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_INFO" ADD CHECK (GLUE_TYPE IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table XXL_TRIGGER_INFO
-- ----------------------------
ALTER TABLE "XXL"."XXL_TRIGGER_INFO" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table XXL_TRIGGER_LOG
-- ----------------------------

-- ----------------------------
-- Checks structure for table XXL_TRIGGER_LOG
-- ----------------------------
ALTER TABLE "XXL"."XXL_TRIGGER_LOG" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_LOG" ADD CHECK ("JOB_GROUP" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_LOG" ADD CHECK ("JOB_ID" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_LOG" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_LOG" ADD CHECK ("JOB_GROUP" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_LOG" ADD CHECK ("JOB_ID" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_LOG" ADD CHECK (ID IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_LOG" ADD CHECK (JOB_GROUP IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_LOG" ADD CHECK (JOB_ID IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table XXL_TRIGGER_LOG
-- ----------------------------
ALTER TABLE "XXL"."XXL_TRIGGER_LOG" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table XXL_TRIGGER_LOGGLUE
-- ----------------------------

-- ----------------------------
-- Checks structure for table XXL_TRIGGER_LOGGLUE
-- ----------------------------
ALTER TABLE "XXL"."XXL_TRIGGER_LOGGLUE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_LOGGLUE" ADD CHECK ("JOB_ID" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_LOGGLUE" ADD CHECK ("GLUE_REMARK" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_LOGGLUE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_LOGGLUE" ADD CHECK ("JOB_ID" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_LOGGLUE" ADD CHECK ("GLUE_REMARK" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_LOGGLUE" ADD CHECK (ID IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_LOGGLUE" ADD CHECK (JOB_ID IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_LOGGLUE" ADD CHECK (GLUE_REMARK IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table XXL_TRIGGER_LOGGLUE
-- ----------------------------
ALTER TABLE "XXL"."XXL_TRIGGER_LOGGLUE" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table XXL_TRIGGER_REGISTRY
-- ----------------------------

-- ----------------------------
-- Checks structure for table XXL_TRIGGER_REGISTRY
-- ----------------------------
ALTER TABLE "XXL"."XXL_TRIGGER_REGISTRY" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_REGISTRY" ADD CHECK ("REGISTRY_GROUP" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_REGISTRY" ADD CHECK ("REGISTRY_KEY" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_REGISTRY" ADD CHECK ("REGISTRY_VALUE" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_REGISTRY" ADD CHECK ("UPDATE_TIME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_REGISTRY" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_REGISTRY" ADD CHECK ("REGISTRY_GROUP" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_REGISTRY" ADD CHECK ("REGISTRY_KEY" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_REGISTRY" ADD CHECK ("REGISTRY_VALUE" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_REGISTRY" ADD CHECK ("UPDATE_TIME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_REGISTRY" ADD CHECK (ID IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_REGISTRY" ADD CHECK (REGISTRY_GROUP IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_REGISTRY" ADD CHECK (REGISTRY_KEY IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_REGISTRY" ADD CHECK (REGISTRY_VALUE IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_REGISTRY" ADD CHECK (UPDATE_TIME IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table XXL_TRIGGER_REGISTRY
-- ----------------------------
ALTER TABLE "XXL"."XXL_TRIGGER_REGISTRY" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table XXL_TRIGGERS
-- ----------------------------

-- ----------------------------
-- Checks structure for table XXL_TRIGGERS
-- ----------------------------
ALTER TABLE "XXL"."XXL_TRIGGERS" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGERS" ADD CHECK ("TRIGGER_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGERS" ADD CHECK ("TRIGGER_GROUP" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGERS" ADD CHECK ("JOB_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGERS" ADD CHECK ("JOB_GROUP" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGERS" ADD CHECK ("TRIGGER_STATE" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGERS" ADD CHECK ("TRIGGER_TYPE" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGERS" ADD CHECK ("START_TIME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGERS" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGERS" ADD CHECK ("TRIGGER_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGERS" ADD CHECK ("TRIGGER_GROUP" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGERS" ADD CHECK ("JOB_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGERS" ADD CHECK ("JOB_GROUP" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGERS" ADD CHECK ("TRIGGER_STATE" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGERS" ADD CHECK ("TRIGGER_TYPE" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGERS" ADD CHECK ("START_TIME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table XXL_TRIGGERS
-- ----------------------------
ALTER TABLE "XXL"."XXL_TRIGGERS" ADD PRIMARY KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP");

-- ----------------------------
-- Foreign Key structure for table "XXL"."XXL_BLOB_TRIGGERS"
-- ----------------------------
ALTER TABLE "XXL"."XXL_BLOB_TRIGGERS" ADD FOREIGN KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP") REFERENCES "XXL"."XXL_TRIGGERS" ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP");

-- ----------------------------
-- Foreign Key structure for table "XXL"."XXL_CRON_TRIGGERS"
-- ----------------------------
ALTER TABLE "XXL"."XXL_CRON_TRIGGERS" ADD FOREIGN KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP") REFERENCES "XXL"."XXL_TRIGGERS" ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP");

-- ----------------------------
-- Foreign Key structure for table "XXL"."XXL_SIMPLE_TRIGGERS"
-- ----------------------------
ALTER TABLE "XXL"."XXL_SIMPLE_TRIGGERS" ADD FOREIGN KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP") REFERENCES "XXL"."XXL_TRIGGERS" ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP");

-- ----------------------------
-- Foreign Key structure for table "XXL"."XXL_SIMPROP_TRIGGERS"
-- ----------------------------
ALTER TABLE "XXL"."XXL_SIMPROP_TRIGGERS" ADD FOREIGN KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP") REFERENCES "XXL"."XXL_TRIGGERS" ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP");

-- ----------------------------
-- Foreign Key structure for table "XXL"."XXL_TRIGGERS"
-- ----------------------------
ALTER TABLE "XXL"."XXL_TRIGGERS" ADD FOREIGN KEY ("SCHED_NAME", "JOB_NAME", "JOB_GROUP") REFERENCES "XXL"."XXL_JOB_DETAILS" ("SCHED_NAME", "JOB_NAME", "JOB_GROUP");
