/*
Navicat Oracle Data Transfer
Oracle Client Version : 11.2.0.1.0

Source Server         : 139.224.69.242（xxl）
Source Server Version : 110200
Source Host           : 139.224.69.242:1521
Source Schema         : XXL

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2017-07-13 18:40:03
*/


-- ----------------------------
-- Table structure for XXL_BLOB_TRIGGERS
-- ----------------------------
DROP TABLE "XXL"."XXL_BLOB_TRIGGERS";
CREATE TABLE "XXL"."XXL_BLOB_TRIGGERS" (
"SCHED_NAME" VARCHAR2(120 BYTE) NOT NULL ,
"TRIGGER_NAME" VARCHAR2(200 BYTE) NOT NULL ,
"TRIGGER_GROUP" VARCHAR2(200 BYTE) NOT NULL ,
"BLOB_DATA" BLOB NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of XXL_BLOB_TRIGGERS
-- ----------------------------

-- ----------------------------
-- Table structure for XXL_CALENDARS
-- ----------------------------
DROP TABLE "XXL"."XXL_CALENDARS";
CREATE TABLE "XXL"."XXL_CALENDARS" (
"SCHED_NAME" VARCHAR2(120 BYTE) NOT NULL ,
"CALENDAR_NAME" VARCHAR2(200 BYTE) NOT NULL ,
"CALENDAR" BLOB NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of XXL_CALENDARS
-- ----------------------------

-- ----------------------------
-- Table structure for XXL_CRON_TRIGGERS
-- ----------------------------
DROP TABLE "XXL"."XXL_CRON_TRIGGERS";
CREATE TABLE "XXL"."XXL_CRON_TRIGGERS" (
"SCHED_NAME" VARCHAR2(120 BYTE) NOT NULL ,
"TRIGGER_NAME" VARCHAR2(200 BYTE) NOT NULL ,
"TRIGGER_GROUP" VARCHAR2(200 BYTE) NOT NULL ,
"CRON_EXPRESSION" VARCHAR2(120 BYTE) NOT NULL ,
"TIME_ZONE_ID" VARCHAR2(80 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of XXL_CRON_TRIGGERS
-- ----------------------------
INSERT INTO "XXL"."XXL_CRON_TRIGGERS" VALUES ('quartzScheduler', '8', '3', '* * * * * ?', 'Asia/Shanghai');
INSERT INTO "XXL"."XXL_CRON_TRIGGERS" VALUES ('quartzScheduler', '4', '3', '* * * * * ?', 'Asia/Shanghai');
INSERT INTO "XXL"."XXL_CRON_TRIGGERS" VALUES ('quartzScheduler', '7', '3', '* * * * * ?', 'Asia/Shanghai');
INSERT INTO "XXL"."XXL_CRON_TRIGGERS" VALUES ('quartzScheduler', '6', '3', '* * * * * ?', 'Asia/Shanghai');

-- ----------------------------
-- Table structure for XXL_FIRED_TRIGGERS
-- ----------------------------
DROP TABLE "XXL"."XXL_FIRED_TRIGGERS";
CREATE TABLE "XXL"."XXL_FIRED_TRIGGERS" (
"SCHED_NAME" VARCHAR2(120 BYTE) NOT NULL ,
"ENTRY_ID" VARCHAR2(95 BYTE) NOT NULL ,
"TRIGGER_NAME" VARCHAR2(200 BYTE) NOT NULL ,
"TRIGGER_GROUP" VARCHAR2(200 BYTE) NOT NULL ,
"INSTANCE_NAME" VARCHAR2(200 BYTE) NOT NULL ,
"FIRED_TIME" NUMBER(13) NOT NULL ,
"SCHED_TIME" NUMBER(13) NOT NULL ,
"PRIORITY" NUMBER(13) NOT NULL ,
"STATE" VARCHAR2(16 BYTE) NOT NULL ,
"JOB_NAME" VARCHAR2(200 BYTE) NULL ,
"JOB_GROUP" VARCHAR2(200 BYTE) NULL ,
"IS_NONCONCURRENT" VARCHAR2(1 BYTE) NULL ,
"REQUESTS_RECOVERY" VARCHAR2(1 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of XXL_FIRED_TRIGGERS
-- ----------------------------
INSERT INTO "XXL"."XXL_FIRED_TRIGGERS" VALUES ('quartzScheduler', 'DESKTOP-MVNDQD114999420565531499942056592', '8', '3', 'DESKTOP-MVNDQD11499942056553', '1499942169483', '1499942169000', '5', 'EXECUTING', '8', '3', '0', '0');

-- ----------------------------
-- Table structure for XXL_JOB_DETAILS
-- ----------------------------
DROP TABLE "XXL"."XXL_JOB_DETAILS";
CREATE TABLE "XXL"."XXL_JOB_DETAILS" (
"SCHED_NAME" VARCHAR2(120 BYTE) NOT NULL ,
"JOB_NAME" VARCHAR2(200 BYTE) NOT NULL ,
"JOB_GROUP" VARCHAR2(200 BYTE) NOT NULL ,
"DESCRIPTION" VARCHAR2(250 BYTE) NULL ,
"JOB_CLASS_NAME" VARCHAR2(250 BYTE) NOT NULL ,
"IS_DURABLE" VARCHAR2(1 BYTE) NOT NULL ,
"IS_NONCONCURRENT" VARCHAR2(1 BYTE) NOT NULL ,
"IS_UPDATE_DATA" VARCHAR2(1 BYTE) NOT NULL ,
"REQUESTS_RECOVERY" VARCHAR2(1 BYTE) NOT NULL ,
"JOB_DATA" BLOB NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of XXL_JOB_DETAILS
-- ----------------------------
INSERT INTO "XXL"."XXL_JOB_DETAILS" VALUES ('quartzScheduler', '8', '3', null, 'com.xxl.job.admin.core.jobbean.RemoteHttpJobBean', '0', '0', '0', '0', HexToRaw('ACED0005737200156F72672E71756172747A2E4A6F62446174614D61709FB083E8BFA9B0CB020000787200266F72672E71756172747A2E7574696C732E537472696E674B65794469727479466C61674D61708208E8C3FBC55D280200015A0013616C6C6F77735472616E7369656E74446174617872001D6F72672E71756172747A2E7574696C732E4469727479466C61674D617013E62EAD28760ACE0200025A000564697274794C00036D617074000F4C6A6176612F7574696C2F4D61703B787000737200116A6176612E7574696C2E486173684D61700507DAC1C31660D103000246000A6C6F6164466163746F724900097468726573686F6C6478703F4000000000000C770800000010000000007800'));
INSERT INTO "XXL"."XXL_JOB_DETAILS" VALUES ('quartzScheduler', '4', '3', null, 'com.xxl.job.admin.core.jobbean.RemoteHttpJobBean', '0', '0', '0', '0', HexToRaw('ACED0005737200156F72672E71756172747A2E4A6F62446174614D61709FB083E8BFA9B0CB020000787200266F72672E71756172747A2E7574696C732E537472696E674B65794469727479466C61674D61708208E8C3FBC55D280200015A0013616C6C6F77735472616E7369656E74446174617872001D6F72672E71756172747A2E7574696C732E4469727479466C61674D617013E62EAD28760ACE0200025A000564697274794C00036D617074000F4C6A6176612F7574696C2F4D61703B787000737200116A6176612E7574696C2E486173684D61700507DAC1C31660D103000246000A6C6F6164466163746F724900097468726573686F6C6478703F4000000000000C770800000010000000007800'));
INSERT INTO "XXL"."XXL_JOB_DETAILS" VALUES ('quartzScheduler', '7', '3', null, 'com.xxl.job.admin.core.jobbean.RemoteHttpJobBean', '0', '0', '0', '0', HexToRaw('ACED0005737200156F72672E71756172747A2E4A6F62446174614D61709FB083E8BFA9B0CB020000787200266F72672E71756172747A2E7574696C732E537472696E674B65794469727479466C61674D61708208E8C3FBC55D280200015A0013616C6C6F77735472616E7369656E74446174617872001D6F72672E71756172747A2E7574696C732E4469727479466C61674D617013E62EAD28760ACE0200025A000564697274794C00036D617074000F4C6A6176612F7574696C2F4D61703B787000737200116A6176612E7574696C2E486173684D61700507DAC1C31660D103000246000A6C6F6164466163746F724900097468726573686F6C6478703F4000000000000C770800000010000000007800'));
INSERT INTO "XXL"."XXL_JOB_DETAILS" VALUES ('quartzScheduler', '6', '3', null, 'com.xxl.job.admin.core.jobbean.RemoteHttpJobBean', '0', '0', '0', '0', HexToRaw('ACED0005737200156F72672E71756172747A2E4A6F62446174614D61709FB083E8BFA9B0CB020000787200266F72672E71756172747A2E7574696C732E537472696E674B65794469727479466C61674D61708208E8C3FBC55D280200015A0013616C6C6F77735472616E7369656E74446174617872001D6F72672E71756172747A2E7574696C732E4469727479466C61674D617013E62EAD28760ACE0200025A000564697274794C00036D617074000F4C6A6176612F7574696C2F4D61703B787000737200116A6176612E7574696C2E486173684D61700507DAC1C31660D103000246000A6C6F6164466163746F724900097468726573686F6C6478703F4000000000000C770800000010000000007800'));

-- ----------------------------
-- Table structure for XXL_LOCKS
-- ----------------------------
DROP TABLE "XXL"."XXL_LOCKS";
CREATE TABLE "XXL"."XXL_LOCKS" (
"SCHED_NAME" VARCHAR2(120 BYTE) NOT NULL ,
"LOCK_NAME" VARCHAR2(40 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of XXL_LOCKS
-- ----------------------------
INSERT INTO "XXL"."XXL_LOCKS" VALUES ('quartzScheduler', 'STATE_ACCESS');
INSERT INTO "XXL"."XXL_LOCKS" VALUES ('quartzScheduler', 'TRIGGER_ACCESS');

-- ----------------------------
-- Table structure for XXL_PAUSED_TRIGGER_GRPS
-- ----------------------------
DROP TABLE "XXL"."XXL_PAUSED_TRIGGER_GRPS";
CREATE TABLE "XXL"."XXL_PAUSED_TRIGGER_GRPS" (
"SCHED_NAME" VARCHAR2(120 BYTE) NOT NULL ,
"TRIGGER_GROUP" VARCHAR2(200 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of XXL_PAUSED_TRIGGER_GRPS
-- ----------------------------

-- ----------------------------
-- Table structure for XXL_SCHEDULER_STATE
-- ----------------------------
DROP TABLE "XXL"."XXL_SCHEDULER_STATE";
CREATE TABLE "XXL"."XXL_SCHEDULER_STATE" (
"SCHED_NAME" VARCHAR2(120 BYTE) NOT NULL ,
"INSTANCE_NAME" VARCHAR2(200 BYTE) NOT NULL ,
"LAST_CHECKIN_TIME" NUMBER(13) NOT NULL ,
"CHECKIN_INTERVAL" NUMBER(13) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of XXL_SCHEDULER_STATE
-- ----------------------------
INSERT INTO "XXL"."XXL_SCHEDULER_STATE" VALUES ('quartzScheduler', 'DESKTOP-MVNDQD11499942056553', '1499942168729', '5000');

-- ----------------------------
-- Table structure for XXL_SIMPLE_TRIGGERS
-- ----------------------------
DROP TABLE "XXL"."XXL_SIMPLE_TRIGGERS";
CREATE TABLE "XXL"."XXL_SIMPLE_TRIGGERS" (
"SCHED_NAME" VARCHAR2(120 BYTE) NOT NULL ,
"TRIGGER_NAME" VARCHAR2(200 BYTE) NOT NULL ,
"TRIGGER_GROUP" VARCHAR2(200 BYTE) NOT NULL ,
"REPEAT_COUNT" NUMBER(7) NOT NULL ,
"REPEAT_INTERVAL" NUMBER(12) NOT NULL ,
"TIMES_TRIGGERED" NUMBER(10) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of XXL_SIMPLE_TRIGGERS
-- ----------------------------

-- ----------------------------
-- Table structure for XXL_SIMPROP_TRIGGERS
-- ----------------------------
DROP TABLE "XXL"."XXL_SIMPROP_TRIGGERS";
CREATE TABLE "XXL"."XXL_SIMPROP_TRIGGERS" (
"SCHED_NAME" VARCHAR2(120 BYTE) NOT NULL ,
"TRIGGER_NAME" VARCHAR2(200 BYTE) NOT NULL ,
"TRIGGER_GROUP" VARCHAR2(200 BYTE) NOT NULL ,
"STR_PROP_1" VARCHAR2(512 BYTE) NULL ,
"STR_PROP_2" VARCHAR2(512 BYTE) NULL ,
"STR_PROP_3" VARCHAR2(512 BYTE) NULL ,
"INT_PROP_1" NUMBER(10) NULL ,
"INT_PROP_2" NUMBER(10) NULL ,
"LONG_PROP_1" NUMBER(13) NULL ,
"LONG_PROP_2" NUMBER(13) NULL ,
"DEC_PROP_1" NUMBER(13,4) NULL ,
"DEC_PROP_2" NUMBER(13,4) NULL ,
"BOOL_PROP_1" VARCHAR2(1 BYTE) NULL ,
"BOOL_PROP_2" VARCHAR2(1 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of XXL_SIMPROP_TRIGGERS
-- ----------------------------

-- ----------------------------
-- Table structure for XXL_TRIGGER_GROUP
-- ----------------------------
DROP TABLE "XXL"."XXL_TRIGGER_GROUP";
CREATE TABLE "XXL"."XXL_TRIGGER_GROUP" (
"ID" NUMBER(11) NOT NULL ,
"APP_NAME" VARCHAR2(64 BYTE) NOT NULL ,
"TITLE" VARCHAR2(12 BYTE) NOT NULL ,
"ORDER" NUMBER(4) DEFAULT '0'  NULL ,
"ADDRESS_TYPE" NUMBER(4) DEFAULT '0'  NULL ,
"ADDRESS_LIST" VARCHAR2(200 BYTE) DEFAULT NULL  NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_GROUP"."APP_NAME" IS '执行器AppName';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_GROUP"."TITLE" IS '执行器名称';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_GROUP"."ORDER" IS '排序';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_GROUP"."ADDRESS_TYPE" IS '执行器地址类型：0=自动注册、1=手动录入';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_GROUP"."ADDRESS_LIST" IS '执行器地址列表，多地址逗号分隔';

-- ----------------------------
-- Records of XXL_TRIGGER_GROUP
-- ----------------------------
INSERT INTO "XXL"."XXL_TRIGGER_GROUP" VALUES ('1', 'xxl-job-executor-example', '示例执行器', '1', '0', null);
INSERT INTO "XXL"."XXL_TRIGGER_GROUP" VALUES ('3', 'xxl-job-executor-example', 'test', '1', '0', null);

-- ----------------------------
-- Table structure for XXL_TRIGGER_INFO
-- ----------------------------
DROP TABLE "XXL"."XXL_TRIGGER_INFO";
CREATE TABLE "XXL"."XXL_TRIGGER_INFO" (
"ID" NUMBER NOT NULL ,
"JOB_GROUP" NUMBER NOT NULL ,
"JOB_CRON" VARCHAR2(128 BYTE) NOT NULL ,
"JOB_DESC" VARCHAR2(255 BYTE) NOT NULL ,
"ADD_TIME" TIMESTAMP(6)  DEFAULT NULL  NULL ,
"UPDATE_TIME" TIMESTAMP(6)  DEFAULT NULL  NULL ,
"AUTHOR" VARCHAR2(64 BYTE) DEFAULT NULL  NULL ,
"ALARM_EMAIL" VARCHAR2(255 BYTE) DEFAULT NULL  NULL ,
"EXECUTOR_ROUTE_STRATEGY" VARCHAR2(50 BYTE) DEFAULT NULL  NULL ,
"EXECUTOR_HANDLER" VARCHAR2(255 BYTE) DEFAULT NULL  NULL ,
"EXECUTOR_PARAM" VARCHAR2(255 BYTE) DEFAULT NULL  NULL ,
"EXECUTOR_BLOCK_STRATEGY" VARCHAR2(50 BYTE) DEFAULT NULL  NULL ,
"EXECUTOR_FAIL_STRATEGY" VARCHAR2(50 BYTE) DEFAULT NULL  NULL ,
"GLUE_TYPE" VARCHAR2(50 BYTE) NOT NULL ,
"GLUE_SOURCE" CLOB NULL ,
"GLUE_REMARK" VARCHAR2(128 BYTE) DEFAULT NULL  NULL ,
"GLUE_UPDATETIME" TIMESTAMP(6)  DEFAULT NULL  NULL ,
"CHILD_JOBKEY" VARCHAR2(255 BYTE) DEFAULT NULL  NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_INFO"."JOB_GROUP" IS '执行器主键ID';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_INFO"."JOB_CRON" IS '任务执行CRON';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_INFO"."AUTHOR" IS '作者';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_INFO"."ALARM_EMAIL" IS '报警邮件';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_INFO"."EXECUTOR_ROUTE_STRATEGY" IS '执行器路由策略';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_INFO"."EXECUTOR_HANDLER" IS '执行器任务handler';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_INFO"."EXECUTOR_PARAM" IS '执行器任务参数';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_INFO"."EXECUTOR_BLOCK_STRATEGY" IS '阻塞处理策略';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_INFO"."EXECUTOR_FAIL_STRATEGY" IS '失败处理策略';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_INFO"."GLUE_TYPE" IS 'GLUE类型';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_INFO"."GLUE_SOURCE" IS 'GLUE源代码';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_INFO"."GLUE_REMARK" IS 'GLUE备注';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_INFO"."GLUE_UPDATETIME" IS 'GLUE更新时间';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_INFO"."CHILD_JOBKEY" IS '子任务Key';

-- ----------------------------
-- Records of XXL_TRIGGER_INFO
-- ----------------------------
INSERT INTO "XXL"."XXL_TRIGGER_INFO" VALUES ('8', '3', '* * * * * ?', 'test4', TO_TIMESTAMP(' 2017-07-13 23:30:26:000000', 'YYYY-MM-DD HH24:MI:SS:FF6'), TO_TIMESTAMP(' 2017-07-13 23:30:26:000000', 'YYYY-MM-DD HH24:MI:SS:FF6'), 'zzrrr', null, 'FIRST', 'demoJobHandler', null, 'SERIAL_EXECUTION', 'FAIL_ALARM', 'BEAN', null, 'GLUE代码初始化', TO_TIMESTAMP(' 2017-07-13 23:30:26:000000', 'YYYY-MM-DD HH24:MI:SS:FF6'), null);
INSERT INTO "XXL"."XXL_TRIGGER_INFO" VALUES ('4', '3', '* * * * * ?', 'test1', TO_TIMESTAMP(' 2017-07-13 17:42:04:000000', 'YYYY-MM-DD HH24:MI:SS:FF6'), TO_TIMESTAMP(' 2017-07-13 17:42:04:000000', 'YYYY-MM-DD HH24:MI:SS:FF6'), 'zy', null, 'FAILOVER', null, null, 'SERIAL_EXECUTION', 'FAIL_ALARM', 'GLUE_GROOVY', 'package com.xxl.job.service.handler;

import com.xxl.job.core.log.XxlJobLogger;
import com.xxl.job.core.biz.model.ReturnT;
import com.xxl.job.core.handler.IJobHandler;

public class DemoGlueJobHandler extends IJobHandler {

	@Override
	public ReturnT<String> execute(String... params) throws Exception {
		XxlJobLogger.log("XXL-JOB, Hello World.");
		return ReturnT.SUCCESS;
	}

}
', 'GLUE代码初始化', TO_TIMESTAMP(' 2017-07-13 17:42:04:000000', 'YYYY-MM-DD HH24:MI:SS:FF6'), null);
INSERT INTO "XXL"."XXL_TRIGGER_INFO" VALUES ('7', '3', '* * * * * ?', 'tt3', TO_TIMESTAMP(' 2017-07-13 22:45:01:000000', 'YYYY-MM-DD HH24:MI:SS:FF6'), TO_TIMESTAMP(' 2017-07-13 22:45:01:000000', 'YYYY-MM-DD HH24:MI:SS:FF6'), 'ttt', null, 'FAILOVER', null, null, 'SERIAL_EXECUTION', 'FAIL_ALARM', 'GLUE_SHELL', '#!/bin/bash
echo "xxl-job: hello shell"

echo "脚本位置：$0"
echo "参数数量：$#"
for param in $*
do
    echo "参数 : $param"
    sleep 1s
done

echo "Good bye!"
exit 0
', 'GLUE代码初始化', TO_TIMESTAMP(' 2017-07-13 22:45:01:000000', 'YYYY-MM-DD HH24:MI:SS:FF6'), null);
INSERT INTO "XXL"."XXL_TRIGGER_INFO" VALUES ('6', '3', '* * * * * ?', 'test3', TO_TIMESTAMP(' 2017-07-13 18:01:38:000000', 'YYYY-MM-DD HH24:MI:SS:FF6'), TO_TIMESTAMP(' 2017-07-13 18:01:38:000000', 'YYYY-MM-DD HH24:MI:SS:FF6'), 'zzee', null, 'FAILOVER', null, null, 'SERIAL_EXECUTION', 'FAIL_ALARM', 'GLUE_PYTHON', '#!/usr/bin/python
# -*- coding: UTF-8 -*-
import time
import sys

print "xxl-job: hello python"
print "脚本文件：", sys.argv[0]
for i in range(1, len(sys.argv)):
	time.sleep(1)
	print "参数", i, sys.argv[i]

print "Good bye!"
exit(0)', 'GLUE代码初始化', TO_TIMESTAMP(' 2017-07-13 18:01:38:000000', 'YYYY-MM-DD HH24:MI:SS:FF6'), null);

-- ----------------------------
-- Table structure for XXL_TRIGGER_LOG
-- ----------------------------
DROP TABLE "XXL"."XXL_TRIGGER_LOG";
CREATE TABLE "XXL"."XXL_TRIGGER_LOG" (
"ID" NUMBER NOT NULL ,
"JOB_GROUP" NUMBER NOT NULL ,
"JOB_ID" NUMBER NOT NULL ,
"GLUE_TYPE" VARCHAR2(50 BYTE) DEFAULT NULL  NULL ,
"EXECUTOR_ADDRESS" VARCHAR2(255 BYTE) DEFAULT NULL  NULL ,
"EXECUTOR_HANDLER" VARCHAR2(255 BYTE) DEFAULT NULL  NULL ,
"EXECUTOR_PARAM" VARCHAR2(255 BYTE) DEFAULT NULL  NULL ,
"TRIGGER_TIME" TIMESTAMP(6)  DEFAULT NULL  NULL ,
"TRIGGER_CODE" VARCHAR2(255 BYTE) DEFAULT NULL  NULL ,
"TRIGGER_MSG" VARCHAR2(2048 BYTE) DEFAULT NULL  NULL ,
"HANDLE_TIME" TIMESTAMP(6)  DEFAULT NULL  NULL ,
"HANDLE_CODE" VARCHAR2(255 BYTE) DEFAULT NULL  NULL ,
"HANDLE_MSG" VARCHAR2(2048 BYTE) DEFAULT NULL  NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_LOG"."JOB_GROUP" IS '执行器主键ID';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_LOG"."JOB_ID" IS '任务，主键ID';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_LOG"."GLUE_TYPE" IS 'GLUE类型';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_LOG"."EXECUTOR_ADDRESS" IS '执行器地址，本次执行的地址';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_LOG"."EXECUTOR_HANDLER" IS '执行器任务handler';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_LOG"."EXECUTOR_PARAM" IS 'executor_param';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_LOG"."TRIGGER_TIME" IS '调度-时间';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_LOG"."TRIGGER_CODE" IS '调度-结果';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_LOG"."TRIGGER_MSG" IS '调度-日志';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_LOG"."HANDLE_TIME" IS '执行-时间';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_LOG"."HANDLE_CODE" IS '执行-状态';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_LOG"."HANDLE_MSG" IS '执行-日志';

-- ----------------------------
-- Records of XXL_TRIGGER_LOG
-- ----------------------------
INSERT INTO "XXL"."XXL_TRIGGER_LOG" VALUES ('880', '3', '4', 'GLUE_GROOVY', '127.0.0.1:9999', null, null, TO_TIMESTAMP(' 2017-07-13 17:12:53:090000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '200', '注册方式：自动注册<br>阻塞处理策略：单机串行<br>失败处理策略：失败告警<br>地址列表：[127.0.0.1:9999]<br>----------------------<br>触发调度：<br>address：127.0.0.1:9999<br>code：200<br>msg：null', TO_TIMESTAMP(' 2017-07-13 17:12:53:553000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '200', null);
INSERT INTO "XXL"."XXL_TRIGGER_LOG" VALUES ('883', '3', '4', 'GLUE_GROOVY', '127.0.0.1:9999', null, null, TO_TIMESTAMP(' 2017-07-13 17:12:55:038000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '200', '注册方式：自动注册<br>阻塞处理策略：单机串行<br>失败处理策略：失败告警<br>地址列表：[127.0.0.1:9999]<br>----------------------<br>触发调度：<br>address：127.0.0.1:9999<br>code：200<br>msg：null', TO_TIMESTAMP(' 2017-07-13 17:12:55:195000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '200', null);
INSERT INTO "XXL"."XXL_TRIGGER_LOG" VALUES ('885', '3', '4', 'GLUE_GROOVY', '127.0.0.1:9999', null, null, TO_TIMESTAMP(' 2017-07-13 17:12:56:164000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '200', '注册方式：自动注册<br>阻塞处理策略：单机串行<br>失败处理策略：失败告警<br>地址列表：[127.0.0.1:9999]<br>----------------------<br>触发调度：<br>address：127.0.0.1:9999<br>code：200<br>msg：null', TO_TIMESTAMP(' 2017-07-13 17:12:56:324000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '200', null);
INSERT INTO "XXL"."XXL_TRIGGER_LOG" VALUES ('887', '3', '4', 'GLUE_GROOVY', '127.0.0.1:9999', null, null, TO_TIMESTAMP(' 2017-07-13 17:12:57:291000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '200', '注册方式：自动注册<br>阻塞处理策略：单机串行<br>失败处理策略：失败告警<br>地址列表：[127.0.0.1:9999]<br>----------------------<br>触发调度：<br>address：127.0.0.1:9999<br>code：200<br>msg：null', TO_TIMESTAMP(' 2017-07-13 17:12:57:446000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '200', null);
INSERT INTO "XXL"."XXL_TRIGGER_LOG" VALUES ('889', '3', '4', 'GLUE_GROOVY', '127.0.0.1:9999', null, null, TO_TIMESTAMP(' 2017-07-13 17:12:58:374000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '200', '注册方式：自动注册<br>阻塞处理策略：单机串行<br>失败处理策略：失败告警<br>地址列表：[127.0.0.1:9999]<br>----------------------<br>触发调度：<br>address：127.0.0.1:9999<br>code：200<br>msg：null', TO_TIMESTAMP(' 2017-07-13 17:12:58:534000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '200', null);
INSERT INTO "XXL"."XXL_TRIGGER_LOG" VALUES ('900', '3', '4', 'GLUE_GROOVY', '127.0.0.1:9999', null, null, TO_TIMESTAMP(' 2017-07-13 17:13:04:567000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '200', '注册方式：自动注册<br>阻塞处理策略：单机串行<br>失败处理策略：失败告警<br>地址列表：[127.0.0.1:9999]<br>----------------------<br>触发调度：<br>address：127.0.0.1:9999<br>code：200<br>msg：null', TO_TIMESTAMP(' 2017-07-13 17:13:04:726000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '200', null);
INSERT INTO "XXL"."XXL_TRIGGER_LOG" VALUES ('917', '3', '4', 'GLUE_GROOVY', '127.0.0.1:9999', null, null, TO_TIMESTAMP(' 2017-07-13 17:13:19:388000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '200', '注册方式：自动注册<br>阻塞处理策略：单机串行<br>失败处理策略：失败告警<br>地址列表：[127.0.0.1:9999]<br>----------------------<br>触发调度：<br>address：127.0.0.1:9999<br>code：200<br>msg：null', TO_TIMESTAMP(' 2017-07-13 17:13:19:546000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '200', null);
INSERT INTO "XXL"."XXL_TRIGGER_LOG" VALUES ('875', '3', '4', 'GLUE_GROOVY', '127.0.0.1:9999', null, null, TO_TIMESTAMP(' 2017-07-13 17:12:50:442000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '200', '注册方式：自动注册<br>阻塞处理策略：单机串行<br>失败处理策略：失败告警<br>地址列表：[127.0.0.1:9999]<br>----------------------<br>触发调度：<br>address：127.0.0.1:9999<br>code：200<br>msg：null', TO_TIMESTAMP(' 2017-07-13 17:12:50:592000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '200', null);

INSERT INTO "XXL"."XXL_TRIGGER_LOG" VALUES ('1632', '3', '8', 'BEAN', '127.0.0.1:9999', 'demoJobHandler', null, TO_TIMESTAMP(' 2017-07-13 18:35:27:834000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '200', '注册方式：自动注册<br>阻塞处理策略：单机串行<br>失败处理策略：失败告警<br>地址列表：[127.0.0.1:9999]<br>----------------------<br>触发调度：<br>address：127.0.0.1:9999<br>code：200<br>msg：null', TO_TIMESTAMP(' 2017-07-13 18:35:28:345000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '200', null);
INSERT INTO "XXL"."XXL_TRIGGER_LOG" VALUES ('1634', '3', '8', 'BEAN', '127.0.0.1:9999', 'demoJobHandler', null, TO_TIMESTAMP(' 2017-07-13 18:35:29:451000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '200', '注册方式：自动注册<br>阻塞处理策略：单机串行<br>失败处理策略：失败告警<br>地址列表：[127.0.0.1:9999]<br>----------------------<br>触发调度：<br>address：127.0.0.1:9999<br>code：200<br>msg：null', TO_TIMESTAMP(' 2017-07-13 18:35:29:707000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '200', null);
INSERT INTO "XXL"."XXL_TRIGGER_LOG" VALUES ('1642', '3', '8', 'BEAN', '127.0.0.1:9999', 'demoJobHandler', null, TO_TIMESTAMP(' 2017-07-13 18:35:36:240000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '200', '注册方式：自动注册<br>阻塞处理策略：单机串行<br>失败处理策略：失败告警<br>地址列表：[127.0.0.1:9999]<br>----------------------<br>触发调度：<br>address：127.0.0.1:9999<br>code：200<br>msg：null', TO_TIMESTAMP(' 2017-07-13 18:35:36:420000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '200', null);
INSERT INTO "XXL"."XXL_TRIGGER_LOG" VALUES ('1645', '3', '8', 'BEAN', '127.0.0.1:9999', 'demoJobHandler', null, TO_TIMESTAMP(' 2017-07-13 18:35:38:465000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '200', '注册方式：自动注册<br>阻塞处理策略：单机串行<br>失败处理策略：失败告警<br>地址列表：[127.0.0.1:9999]<br>----------------------<br>触发调度：<br>address：127.0.0.1:9999<br>code：200<br>msg：null', TO_TIMESTAMP(' 2017-07-13 18:35:38:636000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '200', null);
INSERT INTO "XXL"."XXL_TRIGGER_LOG" VALUES ('1667', '3', '8', 'BEAN', '127.0.0.1:9999', 'demoJobHandler', null, TO_TIMESTAMP(' 2017-07-13 18:36:02:111000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '200', '注册方式：自动注册<br>阻塞处理策略：单机串行<br>失败处理策略：失败告警<br>地址列表：[127.0.0.1:9999]<br>----------------------<br>触发调度：<br>address：127.0.0.1:9999<br>code：200<br>msg：null', TO_TIMESTAMP(' 2017-07-13 18:36:02:260000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '200', null);
INSERT INTO "XXL"."XXL_TRIGGER_LOG" VALUES ('1669', '3', '8', 'BEAN', '127.0.0.1:9999', 'demoJobHandler', null, TO_TIMESTAMP(' 2017-07-13 18:36:04:302000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '200', '注册方式：自动注册<br>阻塞处理策略：单机串行<br>失败处理策略：失败告警<br>地址列表：[127.0.0.1:9999]<br>----------------------<br>触发调度：<br>address：127.0.0.1:9999<br>code：200<br>msg：null', TO_TIMESTAMP(' 2017-07-13 18:36:04:440000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '200', null);
INSERT INTO "XXL"."XXL_TRIGGER_LOG" VALUES ('1672', '3', '8', 'BEAN', '127.0.0.1:9999', 'demoJobHandler', null, TO_TIMESTAMP(' 2017-07-13 18:36:06:428000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '200', '注册方式：自动注册<br>阻塞处理策略：单机串行<br>失败处理策略：失败告警<br>地址列表：[127.0.0.1:9999]<br>----------------------<br>触发调度：<br>address：127.0.0.1:9999<br>code：200<br>msg：null', TO_TIMESTAMP(' 2017-07-13 18:36:06:571000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '200', null);

-- ----------------------------
-- Table structure for XXL_TRIGGER_LOGGLUE
-- ----------------------------
DROP TABLE "XXL"."XXL_TRIGGER_LOGGLUE";
CREATE TABLE "XXL"."XXL_TRIGGER_LOGGLUE" (
"ID" NUMBER NOT NULL ,
"JOB_ID" NUMBER NOT NULL ,
"GLUE_TYPE" VARCHAR2(50 BYTE) DEFAULT NULL  NULL ,
"GLUE_SOURCE" CLOB NULL ,
"GLUE_REMARK" VARCHAR2(128 BYTE) NOT NULL ,
"ADD_TIME" TIMESTAMP(6)  NULL ,
"UPDATE_TIME" TIMESTAMP(6)  NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_LOGGLUE"."JOB_ID" IS '任务，主键ID';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_LOGGLUE"."GLUE_TYPE" IS 'GLUE类型';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_LOGGLUE"."GLUE_SOURCE" IS 'GLUE源代码';
COMMENT ON COLUMN "XXL"."XXL_TRIGGER_LOGGLUE"."GLUE_REMARK" IS 'GLUE备注';

-- ----------------------------
-- Records of XXL_TRIGGER_LOGGLUE
-- ----------------------------

-- ----------------------------
-- Table structure for XXL_TRIGGER_REGISTRY
-- ----------------------------
DROP TABLE "XXL"."XXL_TRIGGER_REGISTRY";
CREATE TABLE "XXL"."XXL_TRIGGER_REGISTRY" (
"ID" NUMBER NOT NULL ,
"REGISTRY_GROUP" VARCHAR2(255 BYTE) NOT NULL ,
"REGISTRY_KEY" VARCHAR2(255 BYTE) NOT NULL ,
"REGISTRY_VALUE" VARCHAR2(255 BYTE) NOT NULL ,
"UPDATE_TIME" TIMESTAMP(6)  NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of XXL_TRIGGER_REGISTRY
-- ----------------------------
INSERT INTO "XXL"."XXL_TRIGGER_REGISTRY" VALUES ('23', 'EXECUTOR', 'xxl-job-executor-example', '127.0.0.1:9999', TO_TIMESTAMP(' 2017-07-13 23:30:51:000000', 'YYYY-MM-DD HH24:MI:SS:FF6'));

-- ----------------------------
-- Table structure for XXL_TRIGGERS
-- ----------------------------
DROP TABLE "XXL"."XXL_TRIGGERS";
CREATE TABLE "XXL"."XXL_TRIGGERS" (
"SCHED_NAME" VARCHAR2(120 BYTE) NOT NULL ,
"TRIGGER_NAME" VARCHAR2(200 BYTE) NOT NULL ,
"TRIGGER_GROUP" VARCHAR2(200 BYTE) NOT NULL ,
"JOB_NAME" VARCHAR2(200 BYTE) NOT NULL ,
"JOB_GROUP" VARCHAR2(200 BYTE) NOT NULL ,
"DESCRIPTION" VARCHAR2(250 BYTE) NULL ,
"NEXT_FIRE_TIME" NUMBER(13) NULL ,
"PREV_FIRE_TIME" NUMBER(13) NULL ,
"PRIORITY" NUMBER(13) NULL ,
"TRIGGER_STATE" VARCHAR2(16 BYTE) NOT NULL ,
"TRIGGER_TYPE" VARCHAR2(8 BYTE) NOT NULL ,
"START_TIME" NUMBER(13) NOT NULL ,
"END_TIME" NUMBER(13) NULL ,
"CALENDAR_NAME" VARCHAR2(200 BYTE) NULL ,
"MISFIRE_INSTR" NUMBER(2) NULL ,
"JOB_DATA" BLOB NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of XXL_TRIGGERS
-- ----------------------------
INSERT INTO "XXL"."XXL_TRIGGERS" VALUES ('quartzScheduler', '8', '3', '8', '3', null, '1499942170000', '1499942169000', '5', 'WAITING', 'CRON', '1499942125000', '0', null, '2', null);
INSERT INTO "XXL"."XXL_TRIGGERS" VALUES ('quartzScheduler', '4', '3', '4', '3', null, '1499937211000', '1499937210000', '5', 'PAUSED', 'CRON', '1499937132000', '0', null, '2', null);
INSERT INTO "XXL"."XXL_TRIGGERS" VALUES ('quartzScheduler', '7', '3', '7', '3', null, '1499942097000', '1499942096000', '5', 'PAUSED', 'CRON', '1499939399000', '0', null, '2', null);
INSERT INTO "XXL"."XXL_TRIGGERS" VALUES ('quartzScheduler', '6', '3', '6', '3', null, '1499938352000', '1499938351000', '5', 'PAUSED', 'CRON', '1499938306000', '0', null, '2', null);

-- ----------------------------
-- Sequence structure for TRIGGER_GROUP_SEQ
-- ----------------------------
DROP SEQUENCE "XXL"."TRIGGER_GROUP_SEQ";
CREATE SEQUENCE "XXL"."TRIGGER_GROUP_SEQ"
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999999999999999999999
 START WITH 1
 NOCACHE ;

-- ----------------------------
-- Sequence structure for TRIGGER_GROUP_SEQUENCE
-- ----------------------------
DROP SEQUENCE "XXL"."TRIGGER_GROUP_SEQUENCE";
CREATE SEQUENCE "XXL"."TRIGGER_GROUP_SEQUENCE"
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999999999999999999999
 START WITH 4
 NOCACHE ;

-- ----------------------------
-- Sequence structure for TRIGGER_INFO_SEQ
-- ----------------------------
DROP SEQUENCE "XXL"."TRIGGER_INFO_SEQ";
CREATE SEQUENCE "XXL"."TRIGGER_INFO_SEQ"
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999999999999999999999
 START WITH 27
 NOCACHE ;

-- ----------------------------
-- Sequence structure for TRIGGER_INFO_SEQUENCE
-- ----------------------------
DROP SEQUENCE "XXL"."TRIGGER_INFO_SEQUENCE";
CREATE SEQUENCE "XXL"."TRIGGER_INFO_SEQUENCE"
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999999999999999999999
 START WITH 9
 NOCACHE ;

-- ----------------------------
-- Sequence structure for TRIGGER_LOG_SEQ
-- ----------------------------
DROP SEQUENCE "XXL"."TRIGGER_LOG_SEQ";
CREATE SEQUENCE "XXL"."TRIGGER_LOG_SEQ"
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999999999999999999999
 START WITH 2
 NOCACHE ;

-- ----------------------------
-- Sequence structure for TRIGGER_LOG_SEQUENCE
-- ----------------------------
DROP SEQUENCE "XXL"."TRIGGER_LOG_SEQUENCE";
CREATE SEQUENCE "XXL"."TRIGGER_LOG_SEQUENCE"
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999999999999999999999
 START WITH 1677
 NOCACHE ;

-- ----------------------------
-- Sequence structure for TRIGGER_LOGGLUE_SEQ
-- ----------------------------
DROP SEQUENCE "XXL"."TRIGGER_LOGGLUE_SEQ";
CREATE SEQUENCE "XXL"."TRIGGER_LOGGLUE_SEQ"
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999999999999999999999
 START WITH 1
 NOCACHE ;

-- ----------------------------
-- Sequence structure for TRIGGER_LOGGLUE_SEQUENCE
-- ----------------------------
DROP SEQUENCE "XXL"."TRIGGER_LOGGLUE_SEQUENCE";
CREATE SEQUENCE "XXL"."TRIGGER_LOGGLUE_SEQUENCE"
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999999999999999999999
 START WITH 2
 NOCACHE ;

-- ----------------------------
-- Sequence structure for TRIGGER_REGISTRY_SEQ
-- ----------------------------
DROP SEQUENCE "XXL"."TRIGGER_REGISTRY_SEQ";
CREATE SEQUENCE "XXL"."TRIGGER_REGISTRY_SEQ"
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999999999999999999999
 START WITH 27
 NOCACHE ;

-- ----------------------------
-- Sequence structure for TRIGGER_REGISTRY_SEQUENCE
-- ----------------------------
DROP SEQUENCE "XXL"."TRIGGER_REGISTRY_SEQUENCE";
CREATE SEQUENCE "XXL"."TRIGGER_REGISTRY_SEQUENCE"
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999999999999999999999
 START WITH 24
 NOCACHE ;

-- ----------------------------
-- Indexes structure for table XXL_BLOB_TRIGGERS
-- ----------------------------

-- ----------------------------
-- Checks structure for table XXL_BLOB_TRIGGERS
-- ----------------------------
ALTER TABLE "XXL"."XXL_BLOB_TRIGGERS" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_BLOB_TRIGGERS" ADD CHECK ("TRIGGER_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_BLOB_TRIGGERS" ADD CHECK ("TRIGGER_GROUP" IS NOT NULL);
ALTER TABLE "XXL"."XXL_BLOB_TRIGGERS" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_BLOB_TRIGGERS" ADD CHECK ("TRIGGER_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_BLOB_TRIGGERS" ADD CHECK ("TRIGGER_GROUP" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table XXL_BLOB_TRIGGERS
-- ----------------------------
ALTER TABLE "XXL"."XXL_BLOB_TRIGGERS" ADD PRIMARY KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP");

-- ----------------------------
-- Indexes structure for table XXL_CALENDARS
-- ----------------------------

-- ----------------------------
-- Checks structure for table XXL_CALENDARS
-- ----------------------------
ALTER TABLE "XXL"."XXL_CALENDARS" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_CALENDARS" ADD CHECK ("CALENDAR_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_CALENDARS" ADD CHECK ("CALENDAR" IS NOT NULL);
ALTER TABLE "XXL"."XXL_CALENDARS" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_CALENDARS" ADD CHECK ("CALENDAR_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_CALENDARS" ADD CHECK ("CALENDAR" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table XXL_CALENDARS
-- ----------------------------
ALTER TABLE "XXL"."XXL_CALENDARS" ADD PRIMARY KEY ("SCHED_NAME", "CALENDAR_NAME");

-- ----------------------------
-- Indexes structure for table XXL_CRON_TRIGGERS
-- ----------------------------

-- ----------------------------
-- Checks structure for table XXL_CRON_TRIGGERS
-- ----------------------------
ALTER TABLE "XXL"."XXL_CRON_TRIGGERS" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_CRON_TRIGGERS" ADD CHECK ("TRIGGER_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_CRON_TRIGGERS" ADD CHECK ("TRIGGER_GROUP" IS NOT NULL);
ALTER TABLE "XXL"."XXL_CRON_TRIGGERS" ADD CHECK ("CRON_EXPRESSION" IS NOT NULL);
ALTER TABLE "XXL"."XXL_CRON_TRIGGERS" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_CRON_TRIGGERS" ADD CHECK ("TRIGGER_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_CRON_TRIGGERS" ADD CHECK ("TRIGGER_GROUP" IS NOT NULL);
ALTER TABLE "XXL"."XXL_CRON_TRIGGERS" ADD CHECK ("CRON_EXPRESSION" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table XXL_CRON_TRIGGERS
-- ----------------------------
ALTER TABLE "XXL"."XXL_CRON_TRIGGERS" ADD PRIMARY KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP");

-- ----------------------------
-- Indexes structure for table XXL_FIRED_TRIGGERS
-- ----------------------------
CREATE INDEX "XXL"."IDX_XXL_FT_INST_JOB_REQ_RCVRY"
ON "XXL"."XXL_FIRED_TRIGGERS" ("SCHED_NAME" ASC, "INSTANCE_NAME" ASC, "REQUESTS_RECOVERY" ASC)
LOGGING
VISIBLE;
CREATE INDEX "XXL"."IDX_XXL_FT_JG"
ON "XXL"."XXL_FIRED_TRIGGERS" ("SCHED_NAME" ASC, "JOB_GROUP" ASC)
LOGGING
VISIBLE;
CREATE INDEX "XXL"."IDX_XXL_FT_J_G"
ON "XXL"."XXL_FIRED_TRIGGERS" ("SCHED_NAME" ASC, "JOB_NAME" ASC, "JOB_GROUP" ASC)
LOGGING
VISIBLE;
CREATE INDEX "XXL"."IDX_XXL_FT_TG"
ON "XXL"."XXL_FIRED_TRIGGERS" ("SCHED_NAME" ASC, "TRIGGER_GROUP" ASC)
LOGGING
VISIBLE;
CREATE INDEX "XXL"."IDX_XXL_FT_TRIG_INST_NAME"
ON "XXL"."XXL_FIRED_TRIGGERS" ("SCHED_NAME" ASC, "INSTANCE_NAME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "XXL"."IDX_XXL_FT_T_G"
ON "XXL"."XXL_FIRED_TRIGGERS" ("SCHED_NAME" ASC, "TRIGGER_NAME" ASC, "TRIGGER_GROUP" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table XXL_FIRED_TRIGGERS
-- ----------------------------
ALTER TABLE "XXL"."XXL_FIRED_TRIGGERS" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_FIRED_TRIGGERS" ADD CHECK ("ENTRY_ID" IS NOT NULL);
ALTER TABLE "XXL"."XXL_FIRED_TRIGGERS" ADD CHECK ("TRIGGER_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_FIRED_TRIGGERS" ADD CHECK ("TRIGGER_GROUP" IS NOT NULL);
ALTER TABLE "XXL"."XXL_FIRED_TRIGGERS" ADD CHECK ("INSTANCE_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_FIRED_TRIGGERS" ADD CHECK ("FIRED_TIME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_FIRED_TRIGGERS" ADD CHECK ("SCHED_TIME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_FIRED_TRIGGERS" ADD CHECK ("PRIORITY" IS NOT NULL);
ALTER TABLE "XXL"."XXL_FIRED_TRIGGERS" ADD CHECK ("STATE" IS NOT NULL);
ALTER TABLE "XXL"."XXL_FIRED_TRIGGERS" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_FIRED_TRIGGERS" ADD CHECK ("ENTRY_ID" IS NOT NULL);
ALTER TABLE "XXL"."XXL_FIRED_TRIGGERS" ADD CHECK ("TRIGGER_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_FIRED_TRIGGERS" ADD CHECK ("TRIGGER_GROUP" IS NOT NULL);
ALTER TABLE "XXL"."XXL_FIRED_TRIGGERS" ADD CHECK ("INSTANCE_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_FIRED_TRIGGERS" ADD CHECK ("FIRED_TIME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_FIRED_TRIGGERS" ADD CHECK ("SCHED_TIME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_FIRED_TRIGGERS" ADD CHECK ("PRIORITY" IS NOT NULL);
ALTER TABLE "XXL"."XXL_FIRED_TRIGGERS" ADD CHECK ("STATE" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table XXL_FIRED_TRIGGERS
-- ----------------------------
ALTER TABLE "XXL"."XXL_FIRED_TRIGGERS" ADD PRIMARY KEY ("SCHED_NAME", "ENTRY_ID");

-- ----------------------------
-- Indexes structure for table XXL_JOB_DETAILS
-- ----------------------------
CREATE INDEX "XXL"."IDX_XXL_J_GRP"
ON "XXL"."XXL_JOB_DETAILS" ("SCHED_NAME" ASC, "JOB_GROUP" ASC)
LOGGING
VISIBLE;
CREATE INDEX "XXL"."IDX_XXL_J_REQ_RECOVERY"
ON "XXL"."XXL_JOB_DETAILS" ("SCHED_NAME" ASC, "REQUESTS_RECOVERY" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table XXL_JOB_DETAILS
-- ----------------------------
ALTER TABLE "XXL"."XXL_JOB_DETAILS" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_JOB_DETAILS" ADD CHECK ("JOB_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_JOB_DETAILS" ADD CHECK ("JOB_GROUP" IS NOT NULL);
ALTER TABLE "XXL"."XXL_JOB_DETAILS" ADD CHECK ("JOB_CLASS_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_JOB_DETAILS" ADD CHECK ("IS_DURABLE" IS NOT NULL);
ALTER TABLE "XXL"."XXL_JOB_DETAILS" ADD CHECK ("IS_NONCONCURRENT" IS NOT NULL);
ALTER TABLE "XXL"."XXL_JOB_DETAILS" ADD CHECK ("IS_UPDATE_DATA" IS NOT NULL);
ALTER TABLE "XXL"."XXL_JOB_DETAILS" ADD CHECK ("REQUESTS_RECOVERY" IS NOT NULL);
ALTER TABLE "XXL"."XXL_JOB_DETAILS" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_JOB_DETAILS" ADD CHECK ("JOB_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_JOB_DETAILS" ADD CHECK ("JOB_GROUP" IS NOT NULL);
ALTER TABLE "XXL"."XXL_JOB_DETAILS" ADD CHECK ("JOB_CLASS_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_JOB_DETAILS" ADD CHECK ("IS_DURABLE" IS NOT NULL);
ALTER TABLE "XXL"."XXL_JOB_DETAILS" ADD CHECK ("IS_NONCONCURRENT" IS NOT NULL);
ALTER TABLE "XXL"."XXL_JOB_DETAILS" ADD CHECK ("IS_UPDATE_DATA" IS NOT NULL);
ALTER TABLE "XXL"."XXL_JOB_DETAILS" ADD CHECK ("REQUESTS_RECOVERY" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table XXL_JOB_DETAILS
-- ----------------------------
ALTER TABLE "XXL"."XXL_JOB_DETAILS" ADD PRIMARY KEY ("SCHED_NAME", "JOB_NAME", "JOB_GROUP");

-- ----------------------------
-- Indexes structure for table XXL_LOCKS
-- ----------------------------

-- ----------------------------
-- Checks structure for table XXL_LOCKS
-- ----------------------------
ALTER TABLE "XXL"."XXL_LOCKS" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_LOCKS" ADD CHECK ("LOCK_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_LOCKS" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_LOCKS" ADD CHECK ("LOCK_NAME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table XXL_LOCKS
-- ----------------------------
ALTER TABLE "XXL"."XXL_LOCKS" ADD PRIMARY KEY ("SCHED_NAME", "LOCK_NAME");

-- ----------------------------
-- Indexes structure for table XXL_PAUSED_TRIGGER_GRPS
-- ----------------------------

-- ----------------------------
-- Checks structure for table XXL_PAUSED_TRIGGER_GRPS
-- ----------------------------
ALTER TABLE "XXL"."XXL_PAUSED_TRIGGER_GRPS" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_PAUSED_TRIGGER_GRPS" ADD CHECK ("TRIGGER_GROUP" IS NOT NULL);
ALTER TABLE "XXL"."XXL_PAUSED_TRIGGER_GRPS" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_PAUSED_TRIGGER_GRPS" ADD CHECK ("TRIGGER_GROUP" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table XXL_PAUSED_TRIGGER_GRPS
-- ----------------------------
ALTER TABLE "XXL"."XXL_PAUSED_TRIGGER_GRPS" ADD PRIMARY KEY ("SCHED_NAME", "TRIGGER_GROUP");

-- ----------------------------
-- Indexes structure for table XXL_SCHEDULER_STATE
-- ----------------------------

-- ----------------------------
-- Checks structure for table XXL_SCHEDULER_STATE
-- ----------------------------
ALTER TABLE "XXL"."XXL_SCHEDULER_STATE" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_SCHEDULER_STATE" ADD CHECK ("INSTANCE_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_SCHEDULER_STATE" ADD CHECK ("LAST_CHECKIN_TIME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_SCHEDULER_STATE" ADD CHECK ("CHECKIN_INTERVAL" IS NOT NULL);
ALTER TABLE "XXL"."XXL_SCHEDULER_STATE" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_SCHEDULER_STATE" ADD CHECK ("INSTANCE_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_SCHEDULER_STATE" ADD CHECK ("LAST_CHECKIN_TIME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_SCHEDULER_STATE" ADD CHECK ("CHECKIN_INTERVAL" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table XXL_SCHEDULER_STATE
-- ----------------------------
ALTER TABLE "XXL"."XXL_SCHEDULER_STATE" ADD PRIMARY KEY ("SCHED_NAME", "INSTANCE_NAME");

-- ----------------------------
-- Indexes structure for table XXL_SIMPLE_TRIGGERS
-- ----------------------------

-- ----------------------------
-- Checks structure for table XXL_SIMPLE_TRIGGERS
-- ----------------------------
ALTER TABLE "XXL"."XXL_SIMPLE_TRIGGERS" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_SIMPLE_TRIGGERS" ADD CHECK ("TRIGGER_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_SIMPLE_TRIGGERS" ADD CHECK ("TRIGGER_GROUP" IS NOT NULL);
ALTER TABLE "XXL"."XXL_SIMPLE_TRIGGERS" ADD CHECK ("REPEAT_COUNT" IS NOT NULL);
ALTER TABLE "XXL"."XXL_SIMPLE_TRIGGERS" ADD CHECK ("REPEAT_INTERVAL" IS NOT NULL);
ALTER TABLE "XXL"."XXL_SIMPLE_TRIGGERS" ADD CHECK ("TIMES_TRIGGERED" IS NOT NULL);
ALTER TABLE "XXL"."XXL_SIMPLE_TRIGGERS" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_SIMPLE_TRIGGERS" ADD CHECK ("TRIGGER_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_SIMPLE_TRIGGERS" ADD CHECK ("TRIGGER_GROUP" IS NOT NULL);
ALTER TABLE "XXL"."XXL_SIMPLE_TRIGGERS" ADD CHECK ("REPEAT_COUNT" IS NOT NULL);
ALTER TABLE "XXL"."XXL_SIMPLE_TRIGGERS" ADD CHECK ("REPEAT_INTERVAL" IS NOT NULL);
ALTER TABLE "XXL"."XXL_SIMPLE_TRIGGERS" ADD CHECK ("TIMES_TRIGGERED" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table XXL_SIMPLE_TRIGGERS
-- ----------------------------
ALTER TABLE "XXL"."XXL_SIMPLE_TRIGGERS" ADD PRIMARY KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP");

-- ----------------------------
-- Indexes structure for table XXL_SIMPROP_TRIGGERS
-- ----------------------------

-- ----------------------------
-- Checks structure for table XXL_SIMPROP_TRIGGERS
-- ----------------------------
ALTER TABLE "XXL"."XXL_SIMPROP_TRIGGERS" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_SIMPROP_TRIGGERS" ADD CHECK ("TRIGGER_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_SIMPROP_TRIGGERS" ADD CHECK ("TRIGGER_GROUP" IS NOT NULL);
ALTER TABLE "XXL"."XXL_SIMPROP_TRIGGERS" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_SIMPROP_TRIGGERS" ADD CHECK ("TRIGGER_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_SIMPROP_TRIGGERS" ADD CHECK ("TRIGGER_GROUP" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table XXL_SIMPROP_TRIGGERS
-- ----------------------------
ALTER TABLE "XXL"."XXL_SIMPROP_TRIGGERS" ADD PRIMARY KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP");

-- ----------------------------
-- Checks structure for table XXL_TRIGGER_GROUP
-- ----------------------------
ALTER TABLE "XXL"."XXL_TRIGGER_GROUP" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_GROUP" ADD CHECK ("APP_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_GROUP" ADD CHECK ("TITLE" IS NOT NULL);

-- ----------------------------
-- Indexes structure for table XXL_TRIGGER_INFO
-- ----------------------------

-- ----------------------------
-- Checks structure for table XXL_TRIGGER_INFO
-- ----------------------------
ALTER TABLE "XXL"."XXL_TRIGGER_INFO" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_INFO" ADD CHECK ("JOB_GROUP" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_INFO" ADD CHECK ("JOB_CRON" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_INFO" ADD CHECK ("JOB_DESC" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_INFO" ADD CHECK ("GLUE_TYPE" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_INFO" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_INFO" ADD CHECK ("JOB_GROUP" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_INFO" ADD CHECK ("JOB_CRON" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_INFO" ADD CHECK ("JOB_DESC" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_INFO" ADD CHECK ("GLUE_TYPE" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_INFO" ADD CHECK (ID IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_INFO" ADD CHECK (JOB_GROUP IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_INFO" ADD CHECK (JOB_CRON IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_INFO" ADD CHECK (JOB_DESC IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_INFO" ADD CHECK (GLUE_TYPE IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table XXL_TRIGGER_INFO
-- ----------------------------
ALTER TABLE "XXL"."XXL_TRIGGER_INFO" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table XXL_TRIGGER_LOG
-- ----------------------------

-- ----------------------------
-- Checks structure for table XXL_TRIGGER_LOG
-- ----------------------------
ALTER TABLE "XXL"."XXL_TRIGGER_LOG" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_LOG" ADD CHECK ("JOB_GROUP" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_LOG" ADD CHECK ("JOB_ID" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_LOG" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_LOG" ADD CHECK ("JOB_GROUP" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_LOG" ADD CHECK ("JOB_ID" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_LOG" ADD CHECK (ID IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_LOG" ADD CHECK (JOB_GROUP IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_LOG" ADD CHECK (JOB_ID IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table XXL_TRIGGER_LOG
-- ----------------------------
ALTER TABLE "XXL"."XXL_TRIGGER_LOG" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table XXL_TRIGGER_LOGGLUE
-- ----------------------------

-- ----------------------------
-- Checks structure for table XXL_TRIGGER_LOGGLUE
-- ----------------------------
ALTER TABLE "XXL"."XXL_TRIGGER_LOGGLUE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_LOGGLUE" ADD CHECK ("JOB_ID" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_LOGGLUE" ADD CHECK ("GLUE_REMARK" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_LOGGLUE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_LOGGLUE" ADD CHECK ("JOB_ID" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_LOGGLUE" ADD CHECK ("GLUE_REMARK" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_LOGGLUE" ADD CHECK (ID IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_LOGGLUE" ADD CHECK (JOB_ID IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_LOGGLUE" ADD CHECK (GLUE_REMARK IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table XXL_TRIGGER_LOGGLUE
-- ----------------------------
ALTER TABLE "XXL"."XXL_TRIGGER_LOGGLUE" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table XXL_TRIGGER_REGISTRY
-- ----------------------------

-- ----------------------------
-- Checks structure for table XXL_TRIGGER_REGISTRY
-- ----------------------------
ALTER TABLE "XXL"."XXL_TRIGGER_REGISTRY" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_REGISTRY" ADD CHECK ("REGISTRY_GROUP" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_REGISTRY" ADD CHECK ("REGISTRY_KEY" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_REGISTRY" ADD CHECK ("REGISTRY_VALUE" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_REGISTRY" ADD CHECK ("UPDATE_TIME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_REGISTRY" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_REGISTRY" ADD CHECK ("REGISTRY_GROUP" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_REGISTRY" ADD CHECK ("REGISTRY_KEY" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_REGISTRY" ADD CHECK ("REGISTRY_VALUE" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_REGISTRY" ADD CHECK ("UPDATE_TIME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_REGISTRY" ADD CHECK (ID IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_REGISTRY" ADD CHECK (REGISTRY_GROUP IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_REGISTRY" ADD CHECK (REGISTRY_KEY IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_REGISTRY" ADD CHECK (REGISTRY_VALUE IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGER_REGISTRY" ADD CHECK (UPDATE_TIME IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table XXL_TRIGGER_REGISTRY
-- ----------------------------
ALTER TABLE "XXL"."XXL_TRIGGER_REGISTRY" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table XXL_TRIGGERS
-- ----------------------------
CREATE INDEX "XXL"."IDX_XXL_T_C"
ON "XXL"."XXL_TRIGGERS" ("SCHED_NAME" ASC, "CALENDAR_NAME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "XXL"."IDX_XXL_T_G"
ON "XXL"."XXL_TRIGGERS" ("SCHED_NAME" ASC, "TRIGGER_GROUP" ASC)
LOGGING
VISIBLE;
CREATE INDEX "XXL"."IDX_XXL_T_J"
ON "XXL"."XXL_TRIGGERS" ("SCHED_NAME" ASC, "JOB_NAME" ASC, "JOB_GROUP" ASC)
LOGGING
VISIBLE;
CREATE INDEX "XXL"."IDX_XXL_T_JG"
ON "XXL"."XXL_TRIGGERS" ("SCHED_NAME" ASC, "JOB_GROUP" ASC)
LOGGING
VISIBLE;
CREATE INDEX "XXL"."IDX_XXL_T_NEXT_FIRE_TIME"
ON "XXL"."XXL_TRIGGERS" ("SCHED_NAME" ASC, "NEXT_FIRE_TIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "XXL"."IDX_XXL_T_NFT_MISFIRE"
ON "XXL"."XXL_TRIGGERS" ("SCHED_NAME" ASC, "MISFIRE_INSTR" ASC, "NEXT_FIRE_TIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "XXL"."IDX_XXL_T_NFT_ST"
ON "XXL"."XXL_TRIGGERS" ("SCHED_NAME" ASC, "TRIGGER_STATE" ASC, "NEXT_FIRE_TIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "XXL"."IDX_XXL_T_NFT_ST_MISFIRE"
ON "XXL"."XXL_TRIGGERS" ("SCHED_NAME" ASC, "MISFIRE_INSTR" ASC, "NEXT_FIRE_TIME" ASC, "TRIGGER_STATE" ASC)
LOGGING
VISIBLE;
CREATE INDEX "XXL"."IDX_XXL_T_NFT_ST_MISFIRE_GRP"
ON "XXL"."XXL_TRIGGERS" ("SCHED_NAME" ASC, "MISFIRE_INSTR" ASC, "NEXT_FIRE_TIME" ASC, "TRIGGER_GROUP" ASC, "TRIGGER_STATE" ASC)
LOGGING
VISIBLE;
CREATE INDEX "XXL"."IDX_XXL_T_N_G_STATE"
ON "XXL"."XXL_TRIGGERS" ("SCHED_NAME" ASC, "TRIGGER_GROUP" ASC, "TRIGGER_STATE" ASC)
LOGGING
VISIBLE;
CREATE INDEX "XXL"."IDX_XXL_T_N_STATE"
ON "XXL"."XXL_TRIGGERS" ("SCHED_NAME" ASC, "TRIGGER_NAME" ASC, "TRIGGER_GROUP" ASC, "TRIGGER_STATE" ASC)
LOGGING
VISIBLE;
CREATE INDEX "XXL"."IDX_XXL_T_STATE"
ON "XXL"."XXL_TRIGGERS" ("SCHED_NAME" ASC, "TRIGGER_STATE" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table XXL_TRIGGERS
-- ----------------------------
ALTER TABLE "XXL"."XXL_TRIGGERS" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGERS" ADD CHECK ("TRIGGER_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGERS" ADD CHECK ("TRIGGER_GROUP" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGERS" ADD CHECK ("JOB_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGERS" ADD CHECK ("JOB_GROUP" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGERS" ADD CHECK ("TRIGGER_STATE" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGERS" ADD CHECK ("TRIGGER_TYPE" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGERS" ADD CHECK ("START_TIME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGERS" ADD CHECK ("SCHED_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGERS" ADD CHECK ("TRIGGER_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGERS" ADD CHECK ("TRIGGER_GROUP" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGERS" ADD CHECK ("JOB_NAME" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGERS" ADD CHECK ("JOB_GROUP" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGERS" ADD CHECK ("TRIGGER_STATE" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGERS" ADD CHECK ("TRIGGER_TYPE" IS NOT NULL);
ALTER TABLE "XXL"."XXL_TRIGGERS" ADD CHECK ("START_TIME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table XXL_TRIGGERS
-- ----------------------------
ALTER TABLE "XXL"."XXL_TRIGGERS" ADD PRIMARY KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP");

-- ----------------------------
-- Foreign Key structure for table "XXL"."XXL_BLOB_TRIGGERS"
-- ----------------------------
ALTER TABLE "XXL"."XXL_BLOB_TRIGGERS" ADD FOREIGN KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP") REFERENCES "XXL"."XXL_TRIGGERS" ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP");

-- ----------------------------
-- Foreign Key structure for table "XXL"."XXL_CRON_TRIGGERS"
-- ----------------------------
ALTER TABLE "XXL"."XXL_CRON_TRIGGERS" ADD FOREIGN KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP") REFERENCES "XXL"."XXL_TRIGGERS" ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP");

-- ----------------------------
-- Foreign Key structure for table "XXL"."XXL_SIMPLE_TRIGGERS"
-- ----------------------------
ALTER TABLE "XXL"."XXL_SIMPLE_TRIGGERS" ADD FOREIGN KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP") REFERENCES "XXL"."XXL_TRIGGERS" ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP");

-- ----------------------------
-- Foreign Key structure for table "XXL"."XXL_SIMPROP_TRIGGERS"
-- ----------------------------
ALTER TABLE "XXL"."XXL_SIMPROP_TRIGGERS" ADD FOREIGN KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP") REFERENCES "XXL"."XXL_TRIGGERS" ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP");

-- ----------------------------
-- Foreign Key structure for table "XXL"."XXL_TRIGGERS"
-- ----------------------------
ALTER TABLE "XXL"."XXL_TRIGGERS" ADD FOREIGN KEY ("SCHED_NAME", "JOB_NAME", "JOB_GROUP") REFERENCES "XXL"."XXL_JOB_DETAILS" ("SCHED_NAME", "JOB_NAME", "JOB_GROUP");
